### ISSUE TITLE
bluetooth: 'NoneType' object has no attribute 'lower' in HA 2022.8

### ISSUE THREAD

**Issue by plesetsk** [TionAPI/HA-tion#110]
## Общая информация
  * **версия Home Assistant**: 
  
  Home Assistant 2022.8.5
Supervisor 2022.08.3
Frontend 20220802.0 - latest

  * **способ установки Home Assistant**:
    [ ] venv
    [v] Docker
    [ ] Home Assistant OS
 * **версия компонента**: v4.0.0
 * **Модель бризера**: S4
 * **версия python-модуля**: 
 [v ] в момент проявления проблемы к бризеру никто не подключен
 [v ] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [v ] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
После перезагрузки ХА интеграция перестала загружаться. 
```
2022-08-18 11:26:21.044 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
авг 18 11:26:21 homeassistant 89050194728a[1285]: 2022-08-18 11:26:21.044 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f7d5b868700>,),kwargs={})
авг 18 11:26:21 homeassistant 89050194728a[1285]: 2022-08-18 11:26:21.044 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='disc'.
авг 18 11:26:21 homeassistant 89050194728a[1285]: 2022-08-18 11:26:21.044 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
авг 18 11:26:21 homeassistant 89050194728a[1285]: 2022-08-18 11:26:21.044 CRITICAL (MainThread) [custom_components.ha_tion_btle] Response is {}
авг 18 11:26:21 homeassistant 89050194728a[1285]: 2022-08-18 11:26:21.048 ERROR (MainThread) [custom_components.ha_tion_btle] Unexpected error fetching Tion Breezer data: 'NoneType' object has no attribute 'lower'
авг 18 11:26:21 homeassistant 89050194728a[1285]: Traceback (most recent call last):
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
авг 18 11:26:21 homeassistant 89050194728a[1285]:     self.data = await self._async_update_data()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
авг 18 11:26:21 homeassistant 89050194728a[1285]:     return await self.update_method()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/config/custom_components/ha_tion_btle/__init__.py", line 109, in async_update_state
авг 18 11:26:21 homeassistant 89050194728a[1285]:     raise e
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/config/custom_components/ha_tion_btle/__init__.py", line 99, in async_update_state
авг 18 11:26:21 homeassistant 89050194728a[1285]:     response = await self.__tion.get()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 208, in get
авг 18 11:26:21 homeassistant 89050194728a[1285]:     await self.get_state_from_breezer()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 188, in get_state_from_breezer
авг 18 11:26:21 homeassistant 89050194728a[1285]:     await self.connect()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 505, in connect
авг 18 11:26:21 homeassistant 89050194728a[1285]:     await self._connect()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 302, in _connect
авг 18 11:26:21 homeassistant 89050194728a[1285]:     await self._try_connect()
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 31, in wrapper
авг 18 11:26:21 homeassistant 89050194728a[1285]:     return await f(*args, **kwargs)
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 295, in _try_connect
авг 18 11:26:21 homeassistant 89050194728a[1285]:     return await self._btle.connect(timeout=5.0)
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 107, in connect
авг 18 11:26:21 homeassistant 89050194728a[1285]:     device = await BleakScannerBlueZDBus.find_device_by_address(
авг 18 11:26:21 homeassistant 89050194728a[1285]:   File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
авг 18 11:26:21 homeassistant 89050194728a[1285]:     device_identifier = device_identifier.lower()
авг 18 11:26:21 homeassistant 89050194728a[1285]: AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by IATkachenko** [comment]
Мы тут сейчас наблюдаем ровно то, чего опались люди из HA в https://github.com/home-assistant/core/pull/76945#issuecomment-1218490076
Я подумаю как это обойти на уровне интеграции.
По идее, нужно подождать пока `bluetooth` интеграция увидит бризер...

**Comment by plesetsk** [comment]
В общем перезагрузил еще раз хост (раз десятый) и вроде бы заработало..

```
авг 18 11:34:14 homeassistant 89050194728a[1285]: 2022-08-18 11:34:14.001 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
авг 18 11:34:14 homeassistant 89050194728a[1285]: 2022-08-18 11:34:14.001 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7fa57b4025c0>,),kwargs={})
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.041 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='connected'
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.137 DEBUG (MainThread) [tion_btle.tion] _enable_notifications done
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.137 DEBUG (MainThread) [tion_btle.tion] _connect done. self.connection_status='connected'.
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.138 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7fa57b4025c0>,),kwargs={'request': bytearray(b'\x80\x10\x00:\xa122\x91c\xf65\x05\xd4\xc3\x8b\xbb\xaa')})
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.138 DEBUG (MainThread) [tion_btle.tion] Writing 8010003aa132329163f63505d4c38bbbaa to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.142 DEBUG (MainThread) [tion_btle.tion] Collecting data
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.339 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 002f003a8f31329163f6355b52420f3d01001403
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.339 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x8f12\x91c\xf65[RB\x0f=\x01\x00\x14\x03')]
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.387 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 401b1b1a2502f3c500efd06f0002c1eb00bdb005
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.388 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x8f12\x91c\xf65[RB\x0f=\x01\x00\x14\x03'), bytearray(b'@\x1b\x1b\x1a%\x02\xf3\xc5\x00\xef\xd0o\x00\x02\xc1\xeb\x00\xbd\xb0\x05')]
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.388 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response c000000000000600abc5
авг 18 11:34:16 homeassistant 89050194728a[1285]: 2022-08-18 11:34:16.388 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x8f12\x91c\xf65[RB\x0f=\x01\x00\x14\x03'), bytearray(b'@\x1b\x1b\x1a%\x02\xf3\xc5\x00\xef\xd0o\x00\x02\xc1\xeb\x00\xbd\xb0\x05'), bytearray(b'\xc0\x00\x00\x00\x00\x00\x06\x00\xab\xc5')]
авг 18 11:34:17 homeassistant 89050194728a[1285]: 2022-08-18 11:34:17.143 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='connected'.
авг 18 11:34:18 homeassistant 89050194728a[1285]: 2022-08-18 11:34:18.994 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'

авг 18 11:35:18 homeassistant 89050194728a[1285]: 2022-08-18 11:35:18.000 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
авг 18 11:35:18 homeassistant 89050194728a[1285]: 2022-08-18 11:35:18.000 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7fa57b4025c0>,),kwargs={})
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.531 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='connected'
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.739 DEBUG (MainThread) [tion_btle.tion] _enable_notifications done
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.739 DEBUG (MainThread) [tion_btle.tion] _connect done. self.connection_status='connected'.
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.739 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7fa57b4025c0>,),kwargs={'request': bytearray(b'\x80\x10\x00:\xa122\tX\x7f\xee5\x8e}\xb5\xbb\xaa')})
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.739 DEBUG (MainThread) [tion_btle.tion] Writing 8010003aa1323209587fee358e7db5bbaa to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.743 DEBUG (MainThread) [tion_btle.tion] Collecting data
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.840 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 002f003a0b313209587fee5b52420f3d01001403
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.840 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x0b12\tX\x7f\xee[RB\x0f=\x01\x00\x14\x03')]
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.890 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 401a1b1b2541f3c5002ed16f00c3c0eb00b9b105
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.890 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x0b12\tX\x7f\xee[RB\x0f=\x01\x00\x14\x03'), bytearray(b'@\x1a\x1b\x1b%A\xf3\xc5\x00.\xd1o\x00\xc3\xc0\xeb\x00\xb9\xb1\x05')]
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.990 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response c0000000000006006686
авг 18 11:35:19 homeassistant 89050194728a[1285]: 2022-08-18 11:35:19.990 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\x0b12\tX\x7f\xee[RB\x0f=\x01\x00\x14\x03'), bytearray(b'@\x1a\x1b\x1b%A\xf3\xc5\x00.\xd1o\x00\xc3\xc0\xeb\x00\xb9\xb1\x05'), bytearray(b'\xc0\x00\x00\x00\x00\x00\x06\x00f\x86')]
авг 18 11:35:20 homeassistant 89050194728a[1285]: 2022-08-18 11:35:20.744 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='connected'.
авг 18 11:35:23 homeassistant 89050194728a[1285]: 2022-08-18 11:35:23.008 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
```

**Comment by IATkachenko** [comment]
Это будет плавующая ошибка, какое-то время (до фикса)

**Comment by plesetsk** [comment]
Спасибо огромное!

**Comment by IATkachenko** [comment]
Исправлено в [v4.0.1](https://github.com/TionAPI/HA-tion/releases/tag/v4.0.1).
