### ISSUE TITLE
Нестабильная связь с бризером [HA 2022.8.0 и выше, интеграция v4.0.1]

### ISSUE THREAD

**Issue by tms320** [TionAPI/HA-tion#112]
## Общая информация
  * **версия Home Assistant**: 2022.9.0
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker (HA supervised)
    [ ] Home Assistant OS
 * **версия компонента**: 4.0.1
 * **модель бризера**: 4S 

[x] в момент проявления проблемы к бризеру никто не подключен
[x] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

После обновления HA до версии 2022.9.0 начались проблемы )
Бризер через раз реагирует на команды изменения скорости и смены режима работы.
В логах примерно такое (пример при попытке изменить скорость):
![image](https://user-images.githubusercontent.com/24802646/189032267-b260e8a1-a149-4853-b192-0d43ddfbf64a.png)

Прикладываю два лога (они достаточно длинные, поэтому в виде файлов):
1. Лог при запуске HA, никакие команды из UI-интерфейса я не подавал:
[HA_logs_start.txt](https://github.com/TionAPI/HA-tion/files/9523498/HA_logs_start.txt)
3. Лог при попытке изменить скорость:
[HA_logs_set_fan_speed.txt](https://github.com/TionAPI/HA-tion/files/9523500/HA_logs_set_fan_speed.txt)

Как я понимаю, они там опять что-то в Блютусе "обновили"...

**Comment by IATkachenko** [comment]
Спасибо, посмотрю.
С 2022.9 я потестироваться еще не успел -- в ближайшее время.
Пока видно что слишком часто вылетает вызов `update_btle_device` который пересоздает объект для работы с bluetooth.

**Comment by plesetsk** [comment]
Похожая ситуация только без частого update_btle_device

```
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.000 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.000 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={})
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.010 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='connected'
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.195 DEBUG (MainThread) [tion_btle.tion] _enable_notifications done
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.195 DEBUG (MainThread) [tion_btle.tion] _connect done. self.connection_status='connected'.
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.195 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={'request': bytearray(b'\x80\x10\x00:\xa122\xb07\xf2FEz"\x18\xbb\xaa')})
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.196 DEBUG (MainThread) [tion_btle.tion] Writing 8010003aa13232b037f246457a2218bbaa to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.197 DEBUG (MainThread) [tion_btle.tion] Collecting data
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.297 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 002f003aa83132b037f246f10798073f01001404
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.298 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xa812\xb07\xf2F\xf1\x07\x98\x07?\x01\x00\x14\x04')]
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.300 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 400b0c1321d711e7004cfc8600864eec007c0e04
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.301 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xa812\xb07\xf2F\xf1\x07\x98\x07?\x01\x00\x14\x04'), bytearray(b'@\x0b\x0c\x13!\xd7\x11\xe7\x00L\xfc\x86\x00\x86N\xec\x00|\x0e\x04')]
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.302 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response c000000000000600b305
сен 13 09:42:06 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:06.302 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xa812\xb07\xf2F\xf1\x07\x98\x07?\x01\x00\x14\x04'), bytearray(b'@\x0b\x0c\x13!\xd7\x11\xe7\x00L\xfc\x86\x00\x86N\xec\x00|\x0e\x04'), bytearray(b'\xc0\x00\x00\x00\x00\x00\x06\x00\xb3\x05')]
сен 13 09:42:07 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:07.198 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='connected'.
сен 13 09:42:09 homeassistant 9e215582ae69[1272]: 2022-09-13 09:42:09.648 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
сен 13 09:43:09 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:09.000 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
сен 13 09:43:09 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:09.000 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={})
сен 13 09:43:09 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:09.461 WARNING (MainThread) [tion_btle.tion] Got exception: [org.bluez.Error.Failed] Software caused connection abort. Will try again

сен 13 09:43:11 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:11.463 DEBUG (MainThread) [tion_btle.tion] Trying 1/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={})
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.046 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='disc'
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.046 WARNING (MainThread) [tion_btle.tion] Got exception Not connected while enabling notifications!
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.048 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='disc'.
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.048 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.048 CRITICAL (MainThread) [custom_components.ha_tion_btle] Response is {}
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: 2022-09-13 09:43:13.049 ERROR (MainThread) [custom_components.ha_tion_btle] Unexpected error fetching Tion Breezer data: Not connected
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: Traceback (most recent call last):
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     self.data = await self._async_update_data()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     return await self.update_method()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/config/custom_components/ha_tion_btle/__init__.py", line 123, in async_update_state
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     raise e
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/config/custom_components/ha_tion_btle/__init__.py", line 113, in async_update_state
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     response = await self.__tion.get()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 208, in get
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     await self.get_state_from_breezer()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 188, in get_state_from_breezer
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     await self.connect()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 505, in connect
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     await self._connect()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 308, in _connect
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     await self._enable_notifications()
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 337, in _enable_notifications
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     raise e
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 334, in _enable_notifications
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     await self._btle.start_notify(self.uuid_notify, self._delegation.handleNotification)
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:   File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 783, in start_notify
сен 13 09:43:13 homeassistant 9e215582ae69[1272]:     raise BleakError("Not connected")
сен 13 09:43:13 homeassistant 9e215582ae69[1272]: bleak.exc.BleakError: Not connected
```

этот блок повторяется очень часто. Спасибо!

**Comment by IATkachenko** [comment]
Это тоже на 2022.9?
Он как-то интересно проваливается через все...

```
Connecting. self.connection_status='disc'.
DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={})
WARNING (MainThread) [tion_btle.tion] Got exception: [org.bluez.Error.Failed] Software caused connection abort. Will try again
DEBUG (MainThread) [tion_btle.tion] Trying 1/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f6a1c6c3430>,),kwargs={})
```
Вот тут мы вышли из `_try_connect()` без exception'ов,
```
DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='disc'
```
но подключение все еще не устанволено:
```
WARNING (MainThread) [tion_btle.tion] Got exception Not connected while enabling notifications!
DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='disc'.
DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
CRITICAL (MainThread) [custom_components.ha_tion_btle] Response is {}
```
Похоже что на стороне `bleak` вся магия происходит.

**Comment by plesetsk** [comment]
> Это тоже на 2022.9? Он как-то интересно проваливается через все...
> 

Home Assistant 2022.9.2

**Comment by IATkachenko** [comment]
Похоже что это -- продолжение #111 

Как я сейчас виду происходящее: когда мы пытаемся получить что-то от бризера в HA тоже происходит какое-то обращение к `bleak`.
Выглядит это примерно так
```
23:48:47.001 INFO [custom_components.ha_tion_btle] Tion instance update started
23:48:47.002 DEBUG [tion_btle.tion] self.__connections_count=0, self.connection_status='disc'
23:48:47.002 DEBUG [tion_btle.tion] semaphore grabbed
23:48:47.002 DEBUG [tion_btle.tion] Connecting. self.connection_status='disc'.
23:48:47.003 DEBUG [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s3.TionS3 object at 0xb1fe4640>,),kwargs={})
23:48:47.003 DEBUG [bleak.backends.bluezdbus.client] Connecting to device @ FF:FF:FF:FF:FF:FF with hci0
23:48:50.095 INFO [custom_components.ha_tion_btle] update_btle_device called with service_info=BluetoothServiceInfoBleak(name='Tion Breezer 3S', address='FF:FF:FF:FF:FF:FF', rssi=-75, manufacturer_data={}, service_data={}, service_uuids=[], source='local', device=FF:FF:FF:FF:FF:FF: Tion Breezer 3S, advertisement=AdvertisementData(local_name='Tion Breezer 3S')), _change=<BluetoothChange.ADVERTISEMENT: 1>
23:48:50.096 DEBUG [bleak.backends.bluezdbus.client] Device disconnected (/org/bluez/hci0/dev_FF_FF_FF_FF_FF_FF)
23:48:50.096 DEBUG [bleak.backends.bluezdbus.client] _cleanup_all(/org/bluez/hci0/dev_FF_FF_FF_FF_FF_FF)
```
и после `_cleanup_all` уже ничего не происходит.

Видимо, нужно разбираться как работать через интейрфейсы HA... Они как раз хотели каких-то врапперов навернуть...

**Comment by IATkachenko** [comment]
В `2022.9.4` все точно также.
Я, наверное чего-то в этой жизни не понимаю, но HA с BT сейчас работает как-то совсем не правильно.
Может чуть позже заведу им issue, потому что я честно вызываю `connect`, а `bleak` выдает
```
[bleak.backends.bluezdbus.client] Connecting to device
[homeassistant.components.bluetooth.manager] hci0: ...
 [custom_components.ha_tion_btle] update_btle_device
[homeassistant.components.bluetooth.manager] hci0: ...
 [custom_components.ha_tion_btle] update_btle_device
[homeassistant.components.bluetooth.manager] hci0: ...
 [custom_components.ha_tion_btle] update_btle_device
[bleak.backends.bluezdbus.client] Device disconnected
```
и все, привет.

**Comment by plesetsk** [comment]
Не знаю на сколько правильно, но я добавил в cron перезагрузку блютуса на хосте каждый час + иногда передергиваю бризер по питанию. стало получше, но это вообще не решение. даже на костыль не тянет.

Еще обратил внимание, что моя автоматизация долбит бризер до тех пор пока он не примет нужное состояние. Это приводит либо к зависанию бризера, либо он срабатывает на n-ную итерацию и дальше работает норм до следующего изменения состояния..

**Comment by IATkachenko** [comment]
Ну, поехали, https://github.com/home-assistant/core/issues/78576

**Comment by fishenebelny** [comment]
Новые обновления в 2022.9.5 потенциально могут улучшить ситуацию?
- Bump bleak-retry-connector to 0.17.1 ([@bdraco](https://github.com/bdraco) - [#78474](https://github.com/home-assistant/core/pull/78474)) ([bluetooth docs](https://www.home-assistant.io/integrations/bluetooth/))
- Fix bluetooth callback matchers when only matching on connectable ([@bdraco](https://github.com/bdraco) - [#78687](https://github.com/home-assistant/core/pull/78687)) ([bluetooth docs](https://www.home-assistant.io/integrations/bluetooth/))

**Comment by plesetsk** [comment]
Обновился. всё тоже самое. 
Обратил внимание еще что со второй попытки отправить управляющую команду она проходит.

Нажимаю **выключить** :

```
сен 19 11:01:45 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:45.709 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
сен 19 11:01:45 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:45.709 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f09f0bef8e0>,),kwargs={})
сен 19 11:01:45 homeassistant systemd[164457]: Reached target Bluetooth.
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:47.592 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='disc'
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:47.592 WARNING (MainThread) [tion_btle.tion] Got exception Not connected while enabling notifications!
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:47.619 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='disc'.
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:47.619 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: 2022-09-19 11:01:47.630 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139679942939680] Not connected
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: Traceback (most recent call last):
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await hass.services.async_call(
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     task.result()
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await service.entity_service_call(
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     future.result()  # pop exception if have
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await coro
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await result
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/config/custom_components/ha_tion_btle/climate.py", line 117, in async_set_hvac_mode
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self._async_set_state(is_on=False)
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/config/custom_components/ha_tion_btle/climate.py", line 239, in _async_set_state
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self.coordinator.set(**kwargs)
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/config/custom_components/ha_tion_btle/__init__.py", line 152, in set
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self.__tion.set(kwargs)
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 247, in set
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self.connect()
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 505, in connect
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self._connect()
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 308, in _connect
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self._enable_notifications()
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 337, in _enable_notifications
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     raise e
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 334, in _enable_notifications
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     await self._btle.start_notify(self.uuid_notify, self._delegation.handleNotification)
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:   File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 805, in start_notify
сен 19 11:01:47 homeassistant bdd91d07f349[1272]:     raise BleakError("Not connected")
сен 19 11:01:47 homeassistant bdd91d07f349[1272]: bleak.exc.BleakError: Not connected
```


Далее второй раз нажимаю **выключить**

```
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.771 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.771 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.TionS4 object at 0x7f09f0bef8e0>,),kwargs={})
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.775 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='connected'
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.991 DEBUG (MainThread) [tion_btle.tion] _enable_notifications done
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.991 DEBUG (MainThread) [tion_btle.tion] _connect done. self.connection_status='connected'.
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.991 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7f09f0bef8e0>,),kwargs={'request': bytearray(b'\x80\x10\x00:\xa122Px\xae\x83f\x98,\xd4\xbb\xaa')})
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.992 DEBUG (MainThread) [tion_btle.tion] Writing 8010003aa132325078ae8366982cd4bbaa to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'
сен 19 11:02:03 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:03.995 DEBUG (MainThread) [tion_btle.tion] Collecting data
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.192 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 002f003a6731325078ae83b22a31e93f81001603
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.192 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:g12Px\xae\x83\xb2*1\xe9?\x81\x00\x16\x03')]
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.194 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 400c0d1420019aee004bf18c008759e6009ee51c
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.194 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:g12Px\xae\x83\xb2*1\xe9?\x81\x00\x16\x03'), bytearray(b'@\x0c\r\x14 \x01\x9a\xee\x00K\xf1\x8c\x00\x87Y\xe6\x00\x9e\xe5\x1c')]
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.195 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response c0000000000006002f78
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.196 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:g12Px\xae\x83\xb2*1\xe9?\x81\x00\x16\x03'), bytearray(b'@\x0c\r\x14 \x01\x9a\xee\x00K\xf1\x8c\x00\x87Y\xe6\x00\x9e\xe5\x1c'), bytearray(b'\xc0\x00\x00\x00\x00\x00\x06\x00/x')]
сен 19 11:02:04 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.996 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b'\x00\x17\x00:m02\xdb\xcd;p\x10Y0A\x1e\x00\x00\x16\x03\xb5\x00\xbb\xaa')
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.997 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7f09f0bef8e0>, bytearray(b'\x00\x17\x00:m02\xdb\xcd;p\x10Y0A\x1e\x00\x00\x16\x03')),kwargs={})
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:04.997 DEBUG (MainThread) [tion_btle.tion] Writing 0017003a6d3032dbcd3b70105930411e00001603 to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.001 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.TionS4 object at 0x7f09f0bef8e0>, bytearray(b'\xc0\xb5\x00\xbb\xaa')),kwargs={})
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.002 DEBUG (MainThread) [tion_btle.tion] Writing c0b500bbaa to 98f00002-3788-83ea-453e-f52244709ddb, self.connection_status='connected'
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.003 DEBUG (MainThread) [tion_btle.tion] Collecting data
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.090 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 002f003ae63132dbcd3b70105930413e81001603
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.091 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xe612\xdb\xcd;p\x10Y0A>\x81\x00\x16\x03')]
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.092 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response 400c0d1420029aee004cf18c008659e600a2e51c
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.092 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xe612\xdb\xcd;p\x10Y0A>\x81\x00\x16\x03'), bytearray(b'@\x0c\r\x14 \x02\x9a\xee\x00L\xf1\x8c\x00\x86Y\xe6\x00\xa2\xe5\x1c')]
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.093 DEBUG (MainThread) [tion_btle.tion] Got data in 17 response c0000000000006009e71
сен 19 11:02:05 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:05.093 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\x00/\x00:\xe612\xdb\xcd;p\x10Y0A>\x81\x00\x16\x03'), bytearray(b'@\x0c\r\x14 \x02\x9a\xee\x00L\xf1\x8c\x00\x86Y\xe6\x00\xa2\xe5\x1c'), bytearray(b'\xc0\x00\x00\x00\x00\x00\x06\x00\x9eq')]
сен 19 11:02:06 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:06.004 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='connected'.
сен 19 11:02:08 homeassistant bdd91d07f349[1272]: 2022-09-19 11:02:08.643 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
```

**Comment by plesetsk** [comment]
Извиняюсь за флуд.

Вот тыкаю кнопки смотрю как реагирует бризер. И вижу четкую закономерность, что на второй тык в короткий промежуток времени он отрабатывает отлично. Моюет быть ему таймаут как то можно добавить, чтобы дольше операцию отрабатывал?

**Comment by UnnamedHero** [comment]
Наверное, я зря со своей 2022.8.7 влезаю, но у меня примерно такие же симптомы. Бризеры рандомно отваливаются. У меня их три штуки. Отваливают рандомно, в независимости от силы сигнала и удалённости от приёмника. Началось после обновления подсистемы Bluetooth в HA. Лечится простой перезагрузкой HA, работает даже для docker версии при перезагрузки из меню HA. Логи пытался собирать, но внутри ничего нет нетипичного. Бризер банально перестаёт отвечать и всё.

**Comment by IATkachenko** [comment]
Не зря, это с 2022.8 началось.

Сейчас есть половинчатое решение:
удаление вот этой строки https://github.com/TionAPI/HA-tion/blob/7ed1ac0ef0ef3133524e6eeeb211cfc7671543b7/custom_components/ha_tion_btle/__init__.py#L211
и следующей (212) -- повышает стабильность работы, на какое-то время.

**Comment by IATkachenko** [comment]
Исправлено в [v4.1.0](https://github.com/TionAPI/HA-tion/releases/tag/v4.1.0).
