### ISSUE TITLE
Не срабатывает подключение к 4S

### ISSUE THREAD

**Issue by p1ne** [TionAPI/HA-tion#126]
## Общая информация
  * **версия Home Assistant**: Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [X] Home Assistant OS
 * **версия компонента**: v4.1.6
 * **Модель бризера**: S4
 * **версия python-модуля**: 
 [X] в момент проявления проблемы к бризеру никто не подключен
 [X] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [X] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
Не проходит попытка подключения к 4S - вне зависимости от установленной галки pairing

## Debug-log
```
2023-10-20 15:15:01.873 ERROR (MainThread) [custom_components.ha_tion_btle.config_flow] Cannot pair and get data. Data is {'model': 'S4', 'name': 'Tion Breezer', 'mac': '<правильный мак>', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; TimeoutError: 
2023-10-20 15:17:01.970 WARNING (MainThread) [py.warnings] /usr/src/homeassistant/homeassistant/data_entry_flow.py:394: RuntimeWarning: coroutine 'Tion.get' was never awaited
  result: FlowResult = await getattr(flow, method)(user_input)

2023-10-20 15:17:11.985 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:17:11.986 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Tion Breezer' for ha_tion_btle integration not ready yet; Retrying in background
2023-10-20 15:17:27.249 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:17:47.343 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:18:17.632 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:18:57.741 INFO (MainThread) [custom_components.ha_tion_btle] Setting up DB:09:CA:5D:3D:95 
2023-10-20 15:18:57.742 INFO (MainThread) [custom_components.ha_tion_btle] Tion instance update started
2023-10-20 15:19:17.919 WARNING (MainThread) [tion_btle.tion] Got exception [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error) while enabling notifications!
2023-10-20 15:19:17.920 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=BleakDBusError('org.bluez.Error.Failed', 'Operation failed with ATT error: 0x0e')
2023-10-20 15:19:17.920 ERROR (MainThread) [custom_components.ha_tion_btle] Unexpected error fetching Tion Breezer data: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_tion_btle/__init__.py", line 127, in async_update_state
    raise e
  File "/config/custom_components/ha_tion_btle/__init__.py", line 117, in async_update_state
    response = await self.__tion.get()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 209, in get
    await self.get_state_from_breezer()
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 189, in get_state_from_breezer
    await self.connect()
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 509, in connect
    await self._connect()
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 309, in _connect
    await self._enable_notifications()
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 341, in _enable_notifications
    raise e
  File "/usr/local/lib/python3.11/site-packages/tion_btle/tion.py", line 338, in _enable_notifications
    await self._btle.start_notify(self.uuid_notify, self._delegation.handleNotification)
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 834, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 958, in start_notify
    assert_reply(reply)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
2023-10-20 15:19:17.948 DEBUG (MainThread) [custom_components.ha_tion_btle] Finished fetching Tion Breezer data in 20.206 seconds (success: False)
2023-10-20 15:20:38.062 INFO (MainThread) [custom_components.ha_tion_btle] Setting up DB:09:CA:5D:3D:95 
2023-10-20 15:20:38.062 INFO (MainThread) [custom_components.ha_tion_btle] Tion instance update started
2023-10-20 15:20:48.154 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:20:48.155 DEBUG (MainThread) [custom_components.ha_tion_btle] Finished fetching Tion Breezer data in 10.092 seconds (success: False)
2023-10-20 15:22:08.351 INFO (MainThread) [custom_components.ha_tion_btle] Setting up DB:09:CA:5D:3D:95 
2023-10-20 15:22:08.352 INFO (MainThread) [custom_components.ha_tion_btle] Tion instance update started
2023-10-20 15:22:18.357 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2023-10-20 15:22:18.357 DEBUG (MainThread) [custom_components.ha_tion_btle] Finished fetching Tion Breezer data in 10.005 seconds (success: False)
```

## Как можно воспроизвети вашу проблему
1. Перевести бризер в режим сопряжения
2. добавить компонент и бризер 4S, нажать Submit со снятой галкой pairing
3. получить ошибку сопряжения
4. перевести бризер в режим сопряжения
5. перейти в добавленный компонент, наблюдать Initializing, Retrying и ошибки в логах

**Comment by IATkachenko** [comment]
Если это -- первая настройка бризера, то проблема в сопряжении бризера и малины.
Нужно курить в сторону сопряжения через `bluetoothctl` или его аналоги и проверить ключи сопряжения, как описано в WiKi. Ну и убедиться что процедура сопряжения выполняется правильно.
