### ISSUE TITLE
Сообщение "Cannot pair and get data" 

### ISSUE THREAD

**Issue by Senyasensey2026** [TionAPI/HA-tion#137]
## Общая информация
  * **версия Home Assistant**:
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [ /] Home Assistant OS
 * **версия компонента**: 
 * **модель бризера**: S4
 * **версия python-модуля**: 

[x ] в момент проявления проблемы к бризеру никто не подключен
[x ] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[ ] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
"Cannot pair and get data" выдаёт такое сообщение при попытке создать пару, при том на бризере в момент попытки создания пары перестаёт мигать синий и горит жёлтый

## Debug-log
```
Returning to first step
2024-12-19 19:00:37.947 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2024-12-19 19:00:37.948 ERROR (MainThread) [custom_components.ha_tion_btle] Timeout fetching Tion Breezer data
2024-12-19 19:00:52.337 DEBUG (MainThread) [custom_components.ha_tion_btle.config_flow] Showing pair info
2024-12-19 19:01:01.975 DEBUG (MainThread) [custom_components.ha_tion_btle.config_flow] Real pairing step
2024-12-19 19:01:01.975 DEBUG (MainThread) [custom_components.ha_tion_btle.config_flow] {'model': 'S4', 'name': 'Tion Breezer', 'mac': 'E1:C9:26:B3:36:9B', 'keep_alive': 60, 'away_temp': 15, 'pair': True}
2024-12-19 19:01:05.558 ERROR (MainThread) [custom_components.ha_tion_btle.config_flow] Cannot pair and get data. Data is {'model': 'S4', 'name': 'Tion Breezer', 'mac': 'E1:C9:26:B3:36:9B', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; RuntimeError: Caught blocking call to sleep with args (3,) inside the event loop by custom integration 'ha_tion_btle' at custom_components/ha_tion_btle/config_flow.py, line 168: time.sleep(3). (offender: /config/custom_components/ha_tion_btle/config_flow.py, line 168: time.sleep(3)), please report it to the author of the 'ha_tion_btle' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep
2024-12-19 19:01:11.751 DEBUG (MainThread) [custom_components.ha_tion_btle.config_flow] Pair failed. Returning to first step

```

## Как можно воспроизвети вашу проблему

Попытка создания пары с бризером

## Дополнительное описание
Я отключил BT на телефоне, единственное где-то дома лежит родной пульт от этого бризера, но по идее он в "спящем режиме" и не должен влиять, других устройств управления нет

**Comment by MadVMax** [comment]
У меня похожая ситуация, удалось решить проблему?
2025-02-11 23:50:42.713 ERROR (MainThread) [custom_components.ha_tion_btle.config_flow] Cannot pair and get data. Data is {'model': 'S4', 'name': 'Tion Breezer', 'mac': 'F1:40:24:19:97:3F', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; MaxTriesExceededError: 
2025-02-11 23:51:04.732 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=TimeoutError()
2025-02-11 23:51:23.699 ERROR (MainThread) [custom_components.ha_tion_btle.config_flow] Cannot pair and get data. Data is {'model': 'S4', 'name': 'Tion Breezer', 'mac': 'F1:40:24:19:97:3F', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; TimeoutError: 
2025-02-11 23:51:32.204 WARNING (MainThread) [tion_btle.tion] Got exception [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error) while enabling notifications!
2025-02-11 23:51:32.206 CRITICAL (MainThread) [custom_components.ha_tion_btle] response={}, e=BleakDBusError('org.bluez.Error.Failed', 'Operation failed with ATT error: 0x0e')
2025-02-11 23:51:32.207 ERROR (MainThread) [custom_components.ha_tion_btle] Unexpected error fetching Breezer 4S data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_tion_btle/__init__.py", line 127, in async_update_state
    raise e
  File "/config/custom_components/ha_tion_btle/__init__.py", line 117, in async_update_state
    response = await self.__tion.get()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 209, in get
    await self.get_state_from_breezer()
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 189, in get_state_from_breezer
    await self.connect()
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 509, in connect
    await self._connect()
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 309, in _connect
    await self._enable_notifications()
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 341, in _enable_notifications
    raise e
  File "/usr/local/lib/python3.13/site-packages/tion_btle/tion.py", line 338, in _enable_notifications
    await self._btle.start_notify(self.uuid_notify, self._delegation.handleNotification)
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 844, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 959, in start_notify
    assert_reply(reply)
    ~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)

**Comment by xapepama** [comment]
Используется [https://www.gl-inet.com/products/gl-s10/](gl-s10) на чипе ESP32, прошивка [https://blakadder.com/gl-s10/](blakadder.com) + Tion Lite

Соединиться с бризером Tion Lite не получается, при этом бризер прерывает поиск и выходит из состояния сопряжения сразу же как к нему пытается обратиться HA. Если не нажимать кнопку сопряжения в HA то прибор так и стоит в режиме сопряжения, т.е. какой то контакт по радио происходит. _Примечание: Но, например любые устройства от Xiaomi которые пуляют по BT бродкасты - соединятся и видятся свободно._ 

В логи HA пишется следующее:
Error writing char/descriptor at handle 0x13, status=5
---
Cannot pair and get data. Data is {'model': 'Lite', 'name': 'Tion Breezer', 'mac': 'E0:48:80:2C:99:E5', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; TionException: ('_get_data_from_breezer', 'Could not get breezer state')

При этом если на хосте HA установлен адаптер BT непосредственно в хосте то Tion Lite подключается без проблем.
