### ISSUE TITLE
Ошибка при добавлении новой интеграции в Home Assistant OS

### ISSUE THREAD

**Issue by alexwizp** [TionAPI/HA-tion#20]
**Метод установки HomeAssistant:** 
образ Raspberry Pi 3 Model B and B+ 32-bit  (https://www.home-assistant.io/hassio/installation/ )
**Версия:** 
Version: 2020.11.0; Operating System: HassOS 4.16
**Версия плагина :** 
v1.4.0-b5.1 (установлен через HACS)
Ошибка при попытке добавить новую интеграцию. 

**Лог:**
`2020-11-14 21:46:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 117, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 530, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 74, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 131, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for tion not found: ['tion-btle==0.2.0a5'].`

**Comment by IATkachenko** [comment]
@alexwizp, добрый день.

pkg_util не может найти `tion-btle==0.2.0a5` [при установке](https://github.com/home-assistant/core/blob/5d83f0a9116be160e885fbba20bbeef02a0849b4/homeassistant/requirements.py#L105) 
```python
 async with pip_lock:
        for req in requirements:
            if pkg_util.is_installed(req):
                continue

            def _install(req: str, kwargs: Dict) -> bool:
                """Install requirement."""
                return pkg_util.install_package(req, **kwargs)

            ret = await hass.async_add_executor_job(_install, req, kwargs)

            if not ret:
                raise RequirementsNotFound(name, [req])
```
, что весьма странно.
Не могли бы вы вот такой эксперимент провести (зайдя на HA по ssh):
```bash
python3 -m venv /tmp/test_venv
. /tmp/test_venv/bin/activate
python3 -m pip install tion-btle==0.2.0a5
ls /tmp/test_venv/lib/python*/site-packages/
```
Возможно есть проблема с их wheels и мне будет нужно туда добавить проект...

**Comment by alexwizp** [comment]
@IATkachenko не выйдет =(, я установил HA используя HassOS образ (https://www.home-assistant.io/hassio/installation/), не VENV

**Comment by IATkachenko** [comment]
@alexwizp, ssh вроде работает в любм случае. 
https://developers.home-assistant.io/docs/operating-system/debugging/
`ssh root@homeassistant.local -p 22222`
Еще есть аддон от commutiny https://community.home-assistant.io/t/home-assistant-community-add-on-ssh-web-terminal/33820

venv в примере -- способ проверить что pip отрабатывает правильно и проблему надо искать в HA.

**Comment by alexwizp** [comment]
поменял в манифесте версию tion-btle на релизную 0.2.2, зависимость установилась, начал показываться попап с конфигурацией плагина, но ошибка при pairing

```
2020-11-17 00:10:16 DEBUG (MainThread) [tion_btle.s3] Pairing
2020-11-17 00:10:16 DEBUG (MainThread) [tion_btle.s3] Connecting
2020-11-17 00:10:17 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random exception
2020-11-17 00:10:19 WARNING (MainThread) [tion_btle.tion] Got exception while _connect: Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random
2020-11-17 00:10:19 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random exception
2020-11-17 00:10:21 WARNING (MainThread) [tion_btle.tion] Got exception while _connect: Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random
2020-11-17 00:10:21 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random exception
2020-11-17 00:10:23 WARNING (MainThread) [tion_btle.tion] Got exception while _connect: Failed to connect to peripheral E3:81:AD:AA:E6:16, addr type: random
2020-11-17 00:10:23 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Result is {}, error: ('_connect', 'Could not connect to E3:81:AD:AA:E6:16')
2020-11-17 00:10:25 ERROR (SyncWorker_13) [pygatt.backends.gatttool.gatttool] Unexpected error when scanning: LE Scan ...
78:0C:FA:97:4E:22 (unknown)
E3:81:AD:AA:E6:16 Tion Breezer 3S
E3:81:AD:AA:E6:16 (unknown)
Disable scan failed: I/O error
2020-11-17 00:10:25 ERROR (SyncWorker_13) [homeassistant.components.bluetooth_le_tracker.device_tracker] Error during Bluetooth LE scan: Unexpected error when scanning: LE Scan ...
78:0C:FA:97:4E:22 (unknown)
E3:81:AD:AA:E6:16 Tion Breezer 3S
E3:81:AD:AA:E6:16 (unknown)
Disable scan failed: I/O error
2020-11-17 00:10:43 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

буду разбираться

**Comment by IATkachenko** [comment]
Модуль v0.2.2 нельзя использовать с beta-версией компонента (на то она и beta).
Поставьте v1.3.3.

На сколько я понял, модуль установился, так что проблемы уже в плоскости подключения. Посмотрите https://github.com/TionAPI/HA-tion/wiki/FAQ может быть там есть полезная информация.

**Comment by IATkachenko** [comment]
@alexwizp, получилось v1.3.3 поставить и запустить?

**Comment by alexwizp** [comment]
v1.3.3 не работает по той же причине Requirements for tion not found: ['tion-btle==0.1.3'].

**Comment by IATkachenko** [comment]
@alexwizp, спасибо.

А через ssh и pip этот пакет ставится?

В любом случае, я тогда попробую поднять HassOS у себя и посмотреть что происходит. 
Извините, это может затянуться.

**Comment by alexwizp** [comment]
Обновился до версии v1.4.0 работает! Спасибо

**Comment by IATkachenko** [comment]
Не понятно как это должно было помочь с `Requirements for tion not found: ['tion-btle==0.1.3']` (я в этом направлении ничего не делал), но, рад что и это тоже исправилось.
