### ISSUE TITLE
Ошибка температуры

### ISSUE THREAD

**Issue by alexanlis** [TionAPI/HA-tion#24]
Добрый день!
Ubuntu 18.04 ,HA 0.116.4 , HACS, HA-tion v1.3.3. +2 тиона.
После наступления отрицательной температуры на улице бризеры отвалились от интеграции. В логах ошибка KeyError: 'out_temp'.
На пульте уличная температура "-2". Если с пульта выключить тион и немного подождать(уличный датчик начинает выдать положительные значения), то тион появляется в HA.
Лог:
```
2020-12-03 20:01:45 DEBUG (MainThread) [tion_btle.tion] Doing _connect. Attempt 3/3
2020-12-03 20:01:45 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2020-12-03 20:01:45 DEBUG (MainThread) [tion_btle.tion] Notify handler is 11
2020-12-03 20:01:45 DEBUG (MainThread) [tion_btle.tion] Will write b'\x01\x00' to 12 handle
2020-12-03 20:01:46 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2020-12-03 20:01:46 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2020-12-03 20:01:46 DEBUG (MainThread) [tion_btle.tion] Writing 3d0100000000000000000000000000000000005a to 6e400002-b5a3-f393-
2020-12-03 20:01:46 DEBUG (MainThread) [tion_btle.tion] Got data in 11 response b310211203001110ffc500133b001e5b003c005a
2020-12-03 20:01:46 CRITICAL (MainThread) [custom_components.tion] Response is {}
2020-12-03 20:01:46 DEBUG (MainThread) [custom_components.tion] Tion instance updated at None
2020-12-03 20:01:46 DEBUG (MainThread) [custom_components.tion] Update fired force = True. Keep connection is False
2020-12-03 20:01:46 DEBUG (MainThread) [tion_btle.tion] Doing _connect. Attempt 1/3
2020-12-03 20:01:47 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2020-12-03 20:01:47 DEBUG (MainThread) [tion_btle.tion] Notify handler is 11
2020-12-03 20:01:47 DEBUG (MainThread) [tion_btle.tion] Will write b'\x01\x00' to 12 handle
2020-12-03 20:01:47 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2020-12-03 20:01:48 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2020-12-03 20:01:48 DEBUG (MainThread) [tion_btle.tion] Writing 3d0100000000000000000000000000000000005a to 6e400002-b5a3-f393-
2020-12-03 20:01:48 DEBUG (MainThread) [tion_btle.tion] Got data in 11 response b310211103001215ff29011402001e3f003c005a
2020-12-03 20:01:48 CRITICAL (MainThread) [custom_components.tion] Response is {}
2020-12-03 20:01:48 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tion platform for climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_pla
    await asyncio.gather(*pending)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 310, in async_add_entiti
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entit
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/tion/climate.py", line 343, in async_added_to_hass
    await self._async_update_state(force=True)
  File "/home/homeassistant/.homeassistant/custom_components/tion/climate.py", line 413, in _async_update_state
    await self._tion_entry.async_update_state(time, force, keep_connection)
  File "/home/homeassistant/.homeassistant/custom_components/tion/__init__.py", line 109, in async_update_state
    raise e
  File "/home/homeassistant/.homeassistant/custom_components/tion/__init__.py", line 93, in async_update_state
    self.__out_temp = response["out_temp"]
KeyError: 'out_temp'

```

![изображение](https://user-images.githubusercontent.com/73129538/101070443-6defa100-35ac-11eb-84b7-1716254f924b.png)

**Comment by IATkachenko** [comment]
Да, проблема известная и в последних версиях python-модуля исправлена.
Но проверить совместимость HA с этим модулем пока не удавалось(времени нет), поэтому релиза еще нет :(
Не позже выходных займусь этим.

**Comment by IATkachenko** [comment]
fixed in v1.3.4
