### ISSUE TITLE
Компоненту не удается подключиться к бризеру в режиме сопряжения

### ISSUE THREAD

**Issue by foxoskol** [TionAPI/HA-tion#27]
**версия компонента**: 1.4.1
**модель бризера**: Lite

Теперь не сопрягается.
так же ошибка в веб интерфейсе:
![Безымянный](https://user-images.githubusercontent.com/71713159/102217567-d2382c00-3eed-11eb-93d7-580c36239fc8.jpg)
В логах:
```
2020-12-15 15:54:51 DEBUG (MainThread) [custom_components.tion.config_flow] Showing pair info
2020-12-15 15:54:52 DEBUG (MainThread) [custom_components.tion.config_flow] Real pairing step
2020-12-15 15:54:52 DEBUG (MainThread) [custom_components.tion.config_flow] {'model': 'Lite', 'name': 'Breezer', 'mac': 'E4:13:**:**:**:**', 'keep_alive': 60, 'away_temp': 15, 'pair': True}
2020-12-15 15:54:52 DEBUG (MainThread) [tion_btle.tion] Pairing
2020-12-15 15:54:54 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E4:13:**:**:**:**, addr type: random exception
2020-12-15 15:54:56 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Data is {'model': 'Lite', 'name': 'Breezer', 'mac': 'E4:13:**:**:**:**', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; BTLEDisconnectError: Failed to connect to peripheral E4:**:**:**:**:**, addr type: random
2020-12-15 15:54:57 DEBUG (MainThread) [custom_components.tion.config_flow] Pair failed. Returning to first step
```
Бризер 100% видеться, так как hcitool lescan(bubnru 20.04) видит устройство:
![Безымянный1](https://user-images.githubusercontent.com/71713159/102218218-b41efb80-3eee-11eb-849e-eedbb19f95a8.jpg)

У меня одного такая проблема?

**Comment by IATkachenko** [comment]
Не похоже.
У вас точно в момент сопряжения к бризеру никто не подключается (телефон, пульт, слишком умный какой-нибудь компоненту, увидевший новый BT девайс)?

**Comment by foxoskol** [comment]
по идее нет, но сейчас на всякий случай, на всех устройствах выключу все.

**Comment by foxoskol** [comment]
выключил вообще все устройства. И самое забавное, что после вот такой неудачно попытке сопряжения, бризер не выходит из режима поиска BT по таймауту.

**Comment by IATkachenko** [comment]
А какая версия bluez у вас на системе?

**Comment by IATkachenko** [comment]
И второй вопрос: через gatttool подключиться получается?

**Comment by foxoskol** [comment]
Версия bluez 5,53. а вот через gatttool что то не коннектится, хотя видит его. Скорей всего у меня проблема в BT, буду копать, и отпишусь.

**Comment by foxoskol** [comment]
Через bluetoothctl получилось и pair установить и подключиться. В плагине все тоже самое.

**Comment by IATkachenko** [comment]
bluepy поддерживает 5.47. Может быть в этом дело.
Хотя, если он ставился через pip, все должно быть правильно.
Попробуйте bluepy переустановить в системе (pip uninstall/install): может быт ьпосле установки blupy обновился bluez и потерялась совместимость.

**Comment by IATkachenko** [comment]
Еще можно попробовать скрипт https://github.com/TionAPI/tion_python/blob/master/tests/lite.py: если вы через bluetoothctl сделали pair он должен сработать. Да и тестироваться будет проще, чем через Home Assistant.

**Comment by foxoskol** [comment]
Видимо проблем еще в ubun20.04 Завтра попробую перекатить на 18.

**Comment by stsergo** [comment]
Аналогичная проблема при подключении к tion lite

bluez 5.44
на хосте висел monitor - до его отключения были ошибки, аналогичные @foxoskol 

После отключения в логах HA:

`2020-12-15 17:39:44 DEBUG (MainThread) [custom_components.tion.config_flow] Showing pair info
2020-12-15 17:39:46 DEBUG (MainThread) [custom_components.tion.config_flow] Real pairing step
2020-12-15 17:39:46 DEBUG (MainThread) [custom_components.tion.config_flow] {'model': 'Lite', 'name': 'Tion Livingroom', 'mac': 'CB:86:F2:3F:3A:CB', 'keep_alive': 60, 'away_temp': 15, 'pair': True}
2020-12-15 17:39:46 DEBUG (MainThread) [tion_btle.tion] Pairing
2020-12-15 17:39:47 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2020-12-15 17:39:47 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2020-12-15 17:39:48 DEBUG (MainThread) [tion_btle.tion] First read done
2020-12-15 17:39:48 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2020-12-15 17:39:48 DEBUG (MainThread) [tion_btle.tion] Connected. BT pairing ...
2020-12-15 17:39:48 DEBUG (MainThread) [tion_btle.tion] disconnected
2020-12-15 17:39:48 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Data is {'model': 'Lite', 'name': 'Tion Livingroom', 'mac': 'CB:86:F2:3F:3A:CB', 'keep_alive': 60, 'away_temp': 15, 'pair': True}, result is {}; KeyError: 'estat'`

При этом lite.py очень даже подключается и считывает данные:
`(homeassistant) server:~ hass$ python3.8 lite.py CB:86:F2:3F:3A:CB
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Doing _try_write. Attempt 1/3
DEBUG:tion_btle.tion:Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
DEBUG:tion_btle.lite:Collecting data
DEBUG:tion_btle.tion:Got data in 18 response 0049003a1231120dd71f8fe77426d586d8010f04
DEBUG:tion_btle.tion:Got data in 18 response 40080f16ee7e5900f4ba58000c939400db6f5901
DEBUG:tion_btle.tion:Got data in 18 response 4000000000000000000000000000000000000000
DEBUG:tion_btle.tion:Got data in 18 response c000000000000a141902040606000047c3
DEBUG:tion_btle.lite:Got 0049003a1231120dd71f8fe77426d586d8010f04 from tion
DEBUG:tion_btle.lite:Got 40080f16ee7e5900f4ba58000c939400db6f5901 from tion
DEBUG:tion_btle.lite:Got 4000000000000000000000000000000000000000 from tion
DEBUG:tion_btle.lite:Got c000000000000a141902040606000047c3 from tion
DEBUG:tion_btle.lite:Data is 86d8010f04080f16ee7e5900f4ba58000c939400db6f59010000000000000000000000000000000000000000000000000a1419020406060000
crc is: 0000
header._package_size = bytearray(b'')
header_commad_type =
DEBUG:__main__:Result is {'state': 'off', 'heater': 'off', 'heating': 'off', 'sound': 'on', 'mode': 'mixed', 'out_temp': 15, 'in_temp': 8, 'heater_temp': 15, 'fan_speed': 4, 'filter_remain': 112.69643518518518, 'time': '17:38', 'request_error_code': 0, 'model': 'Lite', 'code': 200, 'device_work_time': 262.0203125, 'electronic_work_time': 67.88423611111111, 'electronic_temp': 22, 'co2_auto_control': '0', 'filter_change_required': '0', 'light': 'on'}
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is off, fan_speed is 4, target_temp is 15`

**Comment by foxoskol** [comment]
@stsergo У Вас получилось запустить lite.py из tion_python-1.1.0/tion_btle/? У меня при попытке запуска:
`Traceback (most recent call last):
  File "lite.py", line 8, in <module>
    from .tion import tion, TionException
ImportError: attempted relative import with no known parent package
`

**Comment by stsergo** [comment]
@foxoskol я его в venv поставил через pip. А файлик для удобства скопировал в домашний каталог

**Comment by foxoskol** [comment]
> @foxoskol я его в venv поставил через pip. А файлик для удобства скопировал в домашний каталог

хм... да по идее из из хост системы должен запускаться. Странно.
у меня HA просто стоит в docker

**Comment by IATkachenko** [comment]
@foxoskol у вас там где запускаете tion_btle не установлен.

**Comment by IATkachenko** [comment]
Проблему, похоже, локализовали в python-модуле: модулю не нужно активировать уведомления во время pairing'a. Похоже бризер воспринимает это как "полезное действие" и завершает pair-процедуру.

**Comment by IATkachenko** [comment]
Попробуйте, пожалуйста, `tion-btle==1.1.1a1` и вот такой скрипт (по аналогии с lite.py) с бризером в режиме сопряжения:
```python
import logging
import sys
from tion_btle.lite import Lite

logging.basicConfig(level=logging.DEBUG)
_LOGGER = logging.getLogger(__name__)
_LOGGER.setLevel("DEBUG")
try:
    mac = sys.argv[1]
    if mac == 'discover':
        _LOGGER.debug("%s", sys.argv)
        mac = 'dummy'
except IndexError:
    mac = "dummy"

device = Lite(mac)
device.pair()
result = device.get()
print("crc is: " + bytes(device._crc).hex())

print("header._package_size = %s" % device._package_size)
print("header_commad_type = %s" % bytes(device._command_type).hex())

_LOGGER.debug("Result is %s " % result)

_LOGGER.info("Initial state: device is %s, light is %s, sound is %s, heater is %s, fan_speed is %d, target_temp is %d",
              device.state,
              device.light,
              device.sound,
              device.heater,
              device.fan_speed,
              device.target_temp
              )
```

**Comment by stsergo** [comment]
@IATkachenko 
```
$ pip3.8 list|grep tion-btle
tion-btle                1.1.1a1
```

```
$ python3.8 1.py CB:86:F2:3F:3A:CB
DEBUG:tion_btle.tion:Pairing
WARNING:tion_btle.tion:Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 471, in pair
    self._connect(False)
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 313, in _connect
    raise e
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
```

**Comment by foxoskol** [comment]
@IATkachenko чет я ступил на счет библиотеки и правда. Извините, видимо вечер.

у меня вот что получилось(из выше предложенного Вами скрипта):
root@homeassistant:/home/fox/tion_python-1.1.0# python3.8 test.py E4:13:**:**:**:**
DEBUG:tion_btle.tion:Pairing
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Connected. BT pairing ...
DEBUG:tion_btle.tion:disconnected
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    device.pair()
  File "/home/fox/tion_python-1.1.0/tion_btle/tion.py", line 475, in pair
    if rsp['estat'][0] == 0 or rsp['estat'][0] == 19 or rsp['code'][0] == 'success':
KeyError: 'estat'

**Comment by IATkachenko** [comment]
@foxoskol, у вас работает как надо даже с notification'ами (те с той же версией что сейчас в production).
С KeyError буду разбираться: возможно я перемудрил с проверкой состояний, но, похоже что у вас все работает и после правки этого бага все заведется в HA.
@stsergo, а у вас вообще подключиться не может: очень похоже что к бризеру кто-то подключился или бризер так думает.

**Comment by stsergo** [comment]
Да, прошу прощения, monitor забыл, что monitor перезапускается, если не запущен(

```
$ python3.8 1.py CB:86:F2:3F:3A:CB
DEBUG:tion_btle.tion:Pairing
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Connected. BT pairing ...
DEBUG:tion_btle.tion:disconnected
Traceback (most recent call last):
  File "1.py", line 17, in <module>
    device.pair()
  File "/home/hass/homeassistant/lib/python3.8/site-packages/tion_btle/tion.py", line 475, in pair
    if rsp['estat'][0] == 0 or rsp['estat'][0] == 19 or rsp['code'][0] == 'success':
KeyError: 'estat'
```

**Comment by IATkachenko** [comment]
Отлично, у вас тоже все работает правильно.
в версии 1.1.1a2 KeyError поправил. Попробуйте ее, пожалуйста.

С ней, по идее, все должно заработать как надо.
И тогда главный вопрос будет к компоненту: чего ж он нам сразу про это не рассказал...

**Comment by stsergo** [comment]
Заработало!)
```
(homeassistant) server:~ hass$ pip3.8 list|grep tion-btle
tion-btle                1.1.1a2
(homeassistant) server:~ hass$ python3.8 /home/hass/1.py CB:86:F2:3F:3A:CB
DEBUG:tion_btle.tion:Pairing
DEBUG:tion_btle.tion:Notifications not enabled by request
DEBUG:tion_btle.tion:Connected. BT pairing ...
DEBUG:tion_btle.tion:Gor response while sending pair command: {'rsp': ['mgmt'], 'code': ['success']}
DEBUG:tion_btle.tion:success
DEBUG:tion_btle.tion:Device-specific pairing ...
DEBUG:tion_btle.tion:Device pair is done
DEBUG:tion_btle.tion:disconnected
DEBUG:tion_btle.tion:Enabling notification
DEBUG:tion_btle.tion:Delegation enabled
DEBUG:tion_btle.tion:First read done
DEBUG:tion_btle.tion:enable_notification is done
DEBUG:tion_btle.tion:Doing _try_write. Attempt 1/3
DEBUG:tion_btle.tion:Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
DEBUG:tion_btle.lite:Collecting data
DEBUG:tion_btle.tion:Got data in 18 response 0049003af731120dd71f8fe77426d586d8010f04
DEBUG:tion_btle.tion:Got data in 18 response 400810179e995900f4ba58000c939400db6f5901
DEBUG:tion_btle.tion:Got data in 18 response 4000000000000000000000000000000000000000
DEBUG:tion_btle.tion:Got data in 18 response c000000000000a1419020406060000f8df
DEBUG:tion_btle.lite:Got 0049003af731120dd71f8fe77426d586d8010f04 from tion
DEBUG:tion_btle.lite:Got 400810179e995900f4ba58000c939400db6f5901 from tion
DEBUG:tion_btle.lite:Got 4000000000000000000000000000000000000000 from tion
DEBUG:tion_btle.lite:Got c000000000000a1419020406060000f8df from tion
DEBUG:tion_btle.lite:Data is 86d8010f040810179e995900f4ba58000c939400db6f59010000000000000000000000000000000000000000000000000a1419020406060000
crc is: 0000
header._package_size = bytearray(b'')
header_commad_type =
DEBUG:__main__:Result is {'state': 'off', 'heater': 'off', 'heating': 'off', 'sound': 'on', 'mode': 'mixed', 'out_temp': 16, 'in_temp': 8, 'heater_temp': 15, 'fan_speed': 4, 'filter_remain': 112.69643518518518, 'time': '19:33', 'request_error_code': 0, 'model': 'Lite', 'code': 200, 'device_work_time': 262.0203125, 'electronic_work_time': 67.96331018518518, 'electronic_temp': 23, 'co2_auto_control': '0', 'filter_change_required': '0', 'light': 'on'}
INFO:__main__:Initial state: device is off, light is on, sound is on, heater is off, fan_speed is 4, target_temp is 15
```

В HA добавился бризер:
```
2020-12-15 19:34:52 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2020-12-15 19:34:52 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] First read done
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.lite] Collecting data
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a4b31120dd71f8fe77426d586d8010f04
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40081016e8995900f4ba58000c939400db6f5901
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000000000000000000
2020-12-15 19:34:53 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a1419020406060000552f
2020-12-15 19:34:54 DEBUG (MainThread) [tion_btle.lite] Got 0049003a4b31120dd71f8fe77426d586d8010f04 from tion
2020-12-15 19:34:54 DEBUG (MainThread) [tion_btle.lite] Got 40081016e8995900f4ba58000c939400db6f5901 from tion
2020-12-15 19:34:54 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000000000000000000 from tion
2020-12-15 19:34:54 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a1419020406060000552f from tion
2020-12-15 19:34:54 DEBUG (MainThread) [tion_btle.lite] Data is 86d8010f04081016e8995900f4ba58000c939400db6f59010000000000000000000000000000000000000000000000000a1419020406060000
2020-12-15 19:34:54 INFO (MainThread) [custom_components.tion] Setting up None
2020-12-15 19:34:54 DEBUG (MainThread) [custom_components.tion] Tion instance updated at None
2020-12-15 19:34:54 DEBUG (MainThread) [custom_components.tion] Update fired force = True. Keep connection is False
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] First read done
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.lite] Collecting data
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003aa031120dd71f8fe77426d586d8010f04
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40081016ea995900f4ba58000c939400db6f5901
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000000000000000000
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a14190204060600007d53
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Got 0049003aa031120dd71f8fe77426d586d8010f04 from tion
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Got 40081016ea995900f4ba58000c939400db6f5901 from tion
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000000000000000000 from tion
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a14190204060600007d53 from tion
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Data is 86d8010f04081016ea995900f4ba58000c939400db6f59010000000000000000000000000000000000000000000000000a1419020406060000
2020-12-15 19:34:56 WARNING (MainThread) [custom_components.tion.climate] No previously saved temperature, setting to 22
2020-12-15 19:34:56 INFO (MainThread) [custom_components.tion.sensor] Init of sensor input temperature for 7f6d858f7d8109ad49e192234d7d1232 (Tion Livingroom)
2020-12-15 19:34:56 INFO (MainThread) [custom_components.tion.sensor] Init of sensor filters remain for 7f6d858f7d8109ad49e192234d7d1232 (Tion Livingroom)
```

**Comment by IATkachenko** [comment]
Отлично. Fix-релиз будет в ближайшее время.
Спасибо за помощь в отладке.

**Comment by stsergo** [comment]
Добавиться то он добавился, но не управляется (

```
2020-12-15 19:38:45 INFO (MainThread) [custom_components.tion.climate] Need to set mode to heat
2020-12-15 19:38:45 INFO (MainThread) [custom_components.tion] Need to set: heater='on', state='on'
2020-12-15 19:38:45 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random exception
2020-12-15 19:38:47 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139816089268768] Failed to connect to peripheral CB:86:F2:3F:3A:CB, addr type: random
    future.result()  # pop exception if have
  File "/home/hass/.homeassistant/custom_components/tion/climate.py", line 258, in async_set_hvac_mode
  File "/home/hass/.homeassistant/custom_components/tion/climate.py", line 403, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/home/hass/.homeassistant/custom_components/tion/__init__.py", line 203, in set
    self.__tion.set(kwargs)
  File "/home/hass/homeassistant/lib/python3.8/site-packages/tion_btle/tion.py", line 247, in set
  File "/home/hass/homeassistant/lib/python3.8/site-packages/tion_btle/tion.py", line 311, in _connect
    _LOGGER.warning("Got %s exception", str(e))
  File "/home/hass/homeassistant/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
2020-12-15 19:38:54 DEBUG (MainThread) [custom_components.tion] Tion instance updated at 2020-12-15 16:38:54.464948+00:00
2020-12-15 19:38:54 DEBUG (MainThread) [custom_components.tion] Update fired force = False. Keep connection is False
2020-12-15 19:38:54 DEBUG (MainThread) [custom_components.tion] Now is 2020-12-15 16:38:54.464948+00:00
```

**Comment by IATkachenko** [comment]
Это стабильное состояние или иногда встречается? Подключение не перехватывает никто?

**Comment by stsergo** [comment]
стабильное. Все, что могло перехватывать подключения - выключено. на этом же хосте через bluetoothctl получается подключиться

**Comment by IATkachenko** [comment]
А просто данные получаются? Те не работает только set или get тоже?

**Comment by stsergo** [comment]
нет, не получаются

**Comment by stsergo** [comment]
Не может быть связано с #23 
Бризеры у меня достаточно новые, возможно тоже прошивка отличается от той, на которой вы внедряли.

**Comment by IATkachenko** [comment]
@stsergo я в ваших логах, которые прикладывали чуть выше, вижу нормальный обмен
```
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003aa031120dd71f8fe77426d586d8010f04
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40081016ea995900f4ba58000c939400db6f5901
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000000000000000000
2020-12-15 19:34:55 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a14190204060600007d53
2020-12-15 19:34:56 DEBUG (MainThread) [tion_btle.lite] Data is 86d8010f04081016ea995900f4ba58000c939400db6f59010000000000000000000000000000000000000000000000000a1419020406060000
```
Те в этой части все работает.
Давайте в новом issue сделаем чисты эксперимент: нужны будут логи когда компонент уже добавлен и HA пытается его обновить. Обновленная версия модуля будет чуть позже.
