### ISSUE TITLE
Периодическая ошибка bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral

### ISSUE THREAD

**Issue by foxoskol** [TionAPI/HA-tion#41]
HA стоит на ubuntu 18.04 в докере.
И периодически при переключении режима вываливается ошибка bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral
Вот полный лог этой ошибке из логфайла
```
2021-02-09 17:51:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140142379827504] Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/tion/climate.py", line 356, in async_set_temperature
    await self._async_set_state(heater_temp=temperature)
  File "/config/custom_components/tion/climate.py", line 403, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 203, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 247, in set
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
```
Кто то с таким сталкивался? Проблема решается повторным выбором режима. Иногда надо 3-4 раза выбрать режим что бы он переключился.

**Comment by IATkachenko** [comment]
Коротко -- все.
Длинно -- давайте разбираться.
Тут проблема не в том что именно вы делаете, а в том что хост не может подключиться к бризеру. Если обычно все работает, то проблемы хоста исключаем.
В момент проявления проблемы к бризеру ТОЧНО никто не подключен (ни телефон, ни пульт)? (думаю что да, потому что до этого был успешный get запрос, см ниже).

Уточните, пожалуйста, версию компонента используете. Она явно не последняя. 
И то что в логе происходит выше тоже хотелось бы видеть. Там до этого точно был лог успешного get-запроса. Вообще хотелось бы увидеть все, начиная с того момента как компонент говорит `Need to set`

**Comment by foxoskol** [comment]
Точно никто не подключен. Потому что проблема имеет очень непредсказуемый характер
Вот лог, сначала идет удачная попытка, потом вот как раз ошибка и потом снова удачная. 
Версия стоит 1.35
Версия HACS 1.11.1
могу впринцепи и обновить.

Лог:
2021-02-09 17:50:41 INFO (MainThread) [custom_components.tion] Need to set: heater_temp=7.0
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] First read done
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.lite] Collecting data
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003ae831120dd71f8f5b55b0a78fd8020502
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40f90c11f309f102c24db2028cea050080eb4803
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000100000200000000
2021-02-09 17:50:42 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a1419020406060000c089
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Got 0049003ae831120dd71f8f5b55b0a78fd8020502 from tion
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Got 40f90c11f309f102c24db2028cea050080eb4803 from tion
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000100000200000000 from tion
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a1419020406060000c089 from tion
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Data is 8fd8020502f90c11f309f102c24db2028cea050080eb48030000000000000000000000010000020000000000000000000a1419020406060000
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b'\x00\x1e\x00:\x010\x12\xcajT\xbd\x87\xb8F8\x07\x00\x02\x07\x02\n\x14\x19\x02\x04\x06`\x00\x00\xbb\xaa)
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Doing _try_write with request=001e003a013012ca6a54bd87b846380700020702
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Writing 001e003a013012ca6a54bd87b846380700020702 to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Doing _try_write with request=c00a1419020406600000bbaa
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Writing c00a1419020406600000bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:50:43 DEBUG (MainThread) [custom_components.tion] Tion instance updated at None
2021-02-09 17:50:43 DEBUG (MainThread) [custom_components.tion] Update fired force = True. Keep connection is False
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] First read done
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:50:43 DEBUG (MainThread) [tion_btle.lite] Collecting data
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a4131120dd71f8f87b846388fd8020702
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40f90b11f509f102c44db2028aea050086eb4803
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000100000200000000
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a141902040606000061e5
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.lite] Got 0049003a4131120dd71f8f87b846388fd8020702 from tion
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.lite] Got 40f90b11f509f102c44db2028aea050086eb4803 from tion
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000100000200000000 from tion
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a141902040606000061e5 from tion
2021-02-09 17:50:44 DEBUG (MainThread) [tion_btle.lite] Data is 8fd8020702f90b11f509f102c44db2028aea050086eb48030000000000000000000000010000020000000000000000000a1419020406060000
2021-02-09 17:50:57 INFO (MainThread) [custom_components.tion] Need to set: heater_temp=0.0
2021-02-09 17:50:59 WARNING (MainThread) [tion_btle.tion] Got Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random exception
2021-02-09 17:51:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140142379827504] Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/tion/climate.py", line 356, in async_set_temperature
    await self._async_set_state(heater_temp=temperature)
  File "/config/custom_components/tion/climate.py", line 403, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 203, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 247, in set
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 311, in _connect
    raise e
  File "/usr/local/lib/python3.8/site-packages/tion_btle/tion.py", line 300, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral E4:13:50:4E:A9:1B, addr type: random
2021-02-09 17:51:06 WARNING (MainThread) [homeassistant.components.switch] Updating command_line switch took longer than the scheduled update interval 0:00:05
2021-02-09 17:51:09 INFO (MainThread) [custom_components.tion] Need to set: heater_temp=0.0
2021-02-09 17:51:10 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-02-09 17:51:10 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] First read done
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Collecting data
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003ae831120dd71f8f87b846388fd8020702
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40f90611100af102df4db2026fea0500d7eb4803
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000100000200000000
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a1419020406060000d98c
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Got 0049003ae831120dd71f8f87b846388fd8020702 from tion
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Got 40f90611100af102df4db2026fea0500d7eb4803 from tion
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000100000200000000 from tion
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a1419020406060000d98c from tion
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Data is 8fd8020702f90611100af102df4db2026fea0500d7eb48030000000000000000000000010000020000000000000000000a1419020406060000
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b\x00\x1e\x00:\xe50\x12\x0ee\xad\xe6\xf0\x99\xeb!\x07\x00\x02\x00\x02\n\x14\x19\x02\x04\x06`\x00\x00\xbb\xaa')
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Doing _try_write with request=001e003ae530120e65ade6f099eb210700020002
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Writing 001e003ae530120e65ade6f099eb210700020002 to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.lite] Doing _try_write with request=c00a1419020406600000bbaa
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:51:11 DEBUG (MainThread) [tion_btle.tion] Writing c00a1419020406600000bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:51:11 DEBUG (MainThread) [custom_components.tion] Tion instance updated at None
2021-02-09 17:51:11 DEBUG (MainThread) [custom_components.tion] Update fired force = True. Keep connection is False
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] First read done
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.lite] Collecting data
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a4131120dd71f8ff099eb218fd8020002
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40f90611110af102e04db2026eea0500daeb4803
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000100000200000000
2021-02-09 17:51:12 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a14190204060600004dca
2021-02-09 17:51:13 DEBUG (MainThread) [tion_btle.lite] Got 0049003a4131120dd71f8ff099eb218fd8020002 from tion
2021-02-09 17:51:13 DEBUG (MainThread) [tion_btle.lite] Got 40f90611110af102e04db2026eea0500daeb4803 from tion
2021-02-09 17:51:13 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000100000200000000 from tion
2021-02-09 17:51:13 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a14190204060600004dca from tion
2021-02-09 17:51:13 DEBUG (MainThread) [tion_btle.lite] Data is 8fd8020002f90611110af102e04db2026eea0500daeb48030000000000000000000000010000020000000000000000000a1419020406060000
2021-02-09 17:51:17 DEBUG (MainThread) [custom_components.tion] Tion instance updated at 2021-02-09 14:51:17.683802+00:00
2021-02-09 17:51:17 DEBUG (MainThread) [custom_components.tion] Update fired force = False. Keep connection is False
2021-02-09 17:51:17 DEBUG (MainThread) [custom_components.tion] Now is 2021-02-09 14:51:17.683802+00:00
2021-02-09 17:51:19 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-02-09 17:51:19 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] First read done
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.lite] Collecting data
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003ae331120dd71f8ff099eb218fd8020002
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 40f90511190af102e84db20266ea0500f2eb4803
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000100000200000000
2021-02-09 17:51:20 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a14190204060600002774
2021-02-09 17:51:21 DEBUG (MainThread) [tion_btle.lite] Got 0049003ae331120dd71f8ff099eb218fd8020002 from tion
2021-02-09 17:51:21 DEBUG (MainThread) [tion_btle.lite] Got 40f90511190af102e84db20266ea0500f2eb4803 from tion
2021-02-09 17:51:21 DEBUG (MainThread) [tion_btle.lite] Got 4000000000000000000000000100000200000000 from tion
2021-02-09 17:51:21 DEBUG (MainThread) [tion_btle.lite] Got c000000000000a14190204060600002774 from tion
2021-02-09 17:51:21 DEBUG (MainThread) [tion_btle.lite] Data is 8fd8020002f90511190af102e84db20266ea0500f2eb48030000000000000000000000010000020000000000000000000a1419020406060000
2021-02-09 17:51:46 WARNING (MainThread) [homeassistant.components.switch] Updating command_line switch took longer than the scheduled update interval 0:00:05

**Comment by IATkachenko** [comment]
Поддержка Lite появилась в 1.4.0, так что будем думать что это -- она.

В логах ничего экстраординарного не видно. Запрос на установку параметра был через 13 секунд после того как был сделан финальный GET. 
Успешный запрос был спустя 25.

Возможно для бризера 13 -- слишком быстро.
Бывает ли так что фэйлятся даже не частые запросы? (например идущие с интервалом в 30 секунд).

Пока решением вижу сделать так, чтобы компонент какое-то время удерживал соединение после запоса (секунд 10-15).

**Comment by foxoskol** [comment]
> Бывает ли так что фэйлятся даже не частые запросы? (например идущие с интервалом в 30 секунд).

Да, бывает. Причем это совершенно непредсказуемо.
Давайте обновлюсь по последней версии, понаблюдаю пару дней что и как, и отпишусь.

**Comment by IATkachenko** [comment]
Там не было существенных правок в этой части... Так что не думаю что ситуация поменяется.

**Comment by foxoskol** [comment]
> Пока решением вижу сделать так, чтобы компонент какое-то время удерживал соединение после запоса (секунд 10-15).

Ну тогда давайте подожду этой Вашей правки, и тогда обновлюсь, и будем тестить.

**Comment by foxoskol** [comment]
> До конца недели сделю правку.

Ок, благодарю, буду ждать.

**Comment by IATkachenko** [comment]
Попробуйте, пожалуйста, v1.6.2-alpha.1. Если ничего (что-нибудь) измениться -- дайте, пожалуйста, знать.

**Comment by foxoskol** [comment]
Поставил выложенную версию. Верно же я понимаю, что для обновления, было достаточно в custom_components заменить папку tion?
Если да, то понаблюдаю пару дней и отпишусь.

**Comment by IATkachenko** [comment]
Да, и перезапустить HA.
На самом деле нужно обновить только manifest.json или обновить пито-модуль до той версии что в Манифесте.

**Comment by foxoskol** [comment]
К сожалению проблема осталась, субъективно стало реже. Но все же осталась.

**Comment by stsergo** [comment]
Если у вас адаптер только для LE используется, то имеет смысл попробовать поправить настройки демона bluetooth `/etc/bluetooth/main.conf`

Врубаем быстрое подключение и только LE стек:
```
ControllerMode = le
FastConnectable = true
```

Визуально стало сильно реже

**Comment by foxoskol** [comment]
Хм, благодарю, сегодня внесу правку и отпишусь тогда.

**Comment by foxoskol** [comment]
похоже правки изменения в коде, совместно с советом @stsergo  помогли. Но пару дней еще надо понаблюдать.
Внес правки @stsergo в хостовую систему(не в докер контейнер). в раздел General.

**Comment by foxoskol** [comment]
Ну вроде как проблема прошла.
Было за все время 2 раза. Но там скорей всего была причина подвисания стека.

**Comment by IATkachenko** [comment]
Отлично. Добавлю совет в WiKi.
