### ISSUE TITLE
не обновляются статусы бризера после включения (Unexpected response (wr))

### ISSUE THREAD

**Issue by UnnamedHero** [TionAPI/HA-tion#52]
## Общая информация
  * **версия Home Assistant**: 2021.7.3
  * **способ установки Home Assistant**:
    [ ] venv
    [X] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 1.8.2
 * **Модель бризера**: Lite
 * **версия python-модуля**: 
 [X] в момент проявления проблемы к бризеру никто не подключен
 [X] bluetooth в системе работает корректно, действий из (WiKi)[https://github.com/TionAPI/HA-tion/wiki/Bluetooth] не требуется
 [X] проблема не похожа ни на одну из (FAQ)[https://github.com/TionAPI/HA-tion/wiki/FAQ]
## Краткое описание 
После любой манипуляции с бризером вылетает ошибка Unexpected response (wr), однако бризер посланную команду выполняет. В результате в приложении не меняется статус бризера (например, он включился, а статус - выключен)
состояние обновляется минут через 5

## Debug-log
```
2021-07-18 18:53:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140347997953424] Unexpected response (wr)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 256, in async_set_hvac_mode
    await self._async_set_state(heater=False, is_on=True)
  File "/config/custom_components/tion/climate.py", line 432, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 205, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 264, in set
    self.disconnect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 567, in disconnect
    self._disconnect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 333, in _disconnect
    self._disable_notifications()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 398, in _disable_notifications
    self.__write_to_notify_handle(setup_data)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 372, in __write_to_notify_handle
    result = self._btle.writeCharacteristic(notify_handle, data, withResponse=need_response)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 416, in _getResp
    self.delegate.handleNotification(hnd, data)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 23, in handleNotification
    self.__topic.read()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
    raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (wr)
```
При выключении включенного бризера такой лог
```
2021-07-18 19:06:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140347967254688] Unexpected response (rd)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 256, in async_set_hvac_mode
    await self._async_set_state(heater=False, is_on=True)
  File "/config/custom_components/tion/climate.py", line 432, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 205, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 255, in set
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 560, in connect
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 307, in _connect
    if self.connection_status == "disc":
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 297, in connection_status
    raise e
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 292, in connection_status
    connection_status = self._btle.getState()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 471, in getState
    status = self.status()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 379, in status
    return self._waitResp(['stat'])
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
    raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (rd)
```
## Как можно воспроизвети вашу проблему

1. включить бризер
2. бризер отреагирует, включится
3. приложение показывает ошибку Unexpected response (wr)
4. Состояние бризера не обновляется
5.  минут через 5 состояние обновится до нормального

**Comment by quank1968** [comment]
Подтверждаю баг, симптомы те же.
HA: core-2021.6.6 supervised, версия компонента: 1.8.2, устройство: Tion Breezer Lite.

**Comment by IATkachenko** [comment]
А до этого работало нормально? И интересует сравнение с v1.8.1, если есть такая возможность.
Собственно v1.8.2 описанную проблему должна была решать.

**Comment by IATkachenko** [comment]
В качестве быстрого фикса можно попробовать закомментировать вызов `self._disable_notifications()` в 333 строке файла `/usr/local/lib/python3.9/site-packages/tion_btle/tion.py`

**Comment by quank1968** [comment]
> А до этого работало нормально? И интересует сравнение с v1.8.1, если есть такая возможность.
> Собственно v1.8.2 описанную проблему должна была решать.

На 1.8.1 проблема аналогичная.

**Comment by quank1968** [comment]
Закомментировал следующие строки:
`    def _disconnect(self):
        if self.connection_status != "disc":
            # if self.__notifications_enabled:
            #    self._disable_notifications()

            self._btle.disconnect()
`
... работает!

**Comment by quank1968** [comment]
Закомментировал часть кода:

`def _disconnect(self):
    if self.connection_status != "disc":
        # if self.__notifications_enabled:
        #    self._disable_notifications()

        self._btle.disconnect()
`

**Comment by quank1968** [comment]
Теперь, вроде как, работает!

**Comment by IATkachenko** [comment]
Спасибо за тесты.
Подумаю как это правильнее исправить.
