### ISSUE TITLE
Не удается подключиться к тиону Lite

### ISSUE THREAD

**Issue by dmdmvl** [TionAPI/HA-tion#54]
## Общая информация
  * **Версия home assistant**: core-2021.8.8
  * **способ установки Home Assistant**:
    [ ] venv
    [ ] Docker
    [x] Home Assistant OS
 * **версия компонента**: 1.8.2
 * **модель бризера**: Lite
 * **версия python-модуля**: 

[x] в момент проявления проблемы к бризеру никто не подключен
[?] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
При попытке добавить бризер Tion Lite через интеграцию в хоум ассистант возникает ошибка после ввода настроек
![image](https://user-images.githubusercontent.com/58520228/133877710-086f1a0a-08f0-4f28-a372-7b2d14d5bf9e.png)

## Debug-log
```
2021-09-18 12:38:37 DEBUG (MainThread) [custom_components.tion.config_flow] Showing pair info
2021-09-18 12:38:38 DEBUG (MainThread) [custom_components.tion.config_flow] Real pairing step
2021-09-18 12:38:38 DEBUG (MainThread) [custom_components.tion.config_flow] {'name': 'Tion Breezer', 'keep_alive': 60, 'away_temp': 15, 'pair': True, 'mac': 'C4:27:B0:5B:96:CD', 'model': 'Lite'}
2021-09-18 12:38:38 DEBUG (MainThread) [tion_btle.tion] Pairing
2021-09-18 12:38:38 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-18 12:38:39 DEBUG (MainThread) [tion_btle.tion] Notifications was not requested
2021-09-18 12:38:39 DEBUG (MainThread) [tion_btle.tion] Connected. BT pairing ...
2021-09-18 12:38:39 DEBUG (MainThread) [tion_btle.tion] Got response while sending pair command: {'rsp': ['mgmt'], 'code': ['mgmterr'], 'estat': [5], 'emsg': ['Authentication Failed']}
2021-09-18 12:38:39 CRITICAL (MainThread) [tion_btle.tion] Unexpected response: {'rsp': ['mgmt'], 'code': ['mgmterr'], 'estat': [5], 'emsg': ['Authentication Failed']}
2021-09-18 12:38:39 CRITICAL (MainThread) [tion_btle.tion] Got exception while pair TionException: ('pair', {'rsp': ['mgmt'], 'code': ['mgmterr'], 'estat': [5], 'emsg': ['Authentication Failed']})
2021-09-18 12:38:39 DEBUG (MainThread) [tion_btle.tion] disconnected
2021-09-18 12:38:39 ERROR (MainThread) [custom_components.tion.config_flow] Cannot pair and get data. Data is {'name': 'Tion Breezer', 'keep_alive': 60, 'away_temp': 15, 'pair': True, 'mac': 'C4:27:B0:5B:96:CD', 'model': 'Lite'}, result is {}; TionException: ('pair', "TionException: ('pair', {'rsp': ['mgmt'], 'code': ['mgmterr'], 'estat': [5], 'emsg': ['Authentication Failed']})")
2021-09-18 12:38:45 DEBUG (MainThread) [custom_components.tion.config_flow] Pair failed. Returning to first step
```

## Как можно воспроизвеcти вашу проблему
1. Включаем на бризере режим сопряжения
2. Добавляем бризер через интеграцию
3. Вводим настройки для подключения
4. Получаем ошибку

## Дополнительное описание
Версия прошивки бризера 054B. К телефону подключается нормально. Пробовал сбрасывать настройки бризера - не помогает.

**Comment by IATkachenko** [comment]
Попробуйте из консоли сделать сопряжение через bluetoothctl. После этого добавить бризер без сопряжения.
Из [Wiki](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) советы не помогают?

**Comment by dmdmvl** [comment]
Добрый день.

При попытке подключиться через bluetoothctl получаю ошибку:
```
[bluetooth]# pair C4:27:B0:5B:96:CD
Device C4:27:B0:5B:96:CD not available
```

Посмотрел FAQ. Кажется советы не подходят: к бризеру никто не подключен, Home Assistant как я понимаю на HASS OS работает из под root, разрешения для root в `bluetooth.conf` есть.

**Comment by IATkachenko** [comment]
Собственно проблема именно в этом (device not avaliable).
Нужно добиться чтобы прошло сопряжение.
Еще можно попробовать подождать некоторое время между попытками (порядка 5-10 минут).
Когда бризер переводите в режим сопряжения bluetoothctl его видит? (scan on)

**Comment by dmdmvl** [comment]
Какая-то магия. Сейчас подключиться удалось.
```
[bluetooth]# pair C4:27:B0:5B:96:CD
Attempting to pair with C4:27:B0:5B:96:CD
[CHG] Device C4:27:B0:5B:96:CD Connected: yes
[CHG] Device C4:27:B0:5B:96:CD UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device C4:27:B0:5B:96:CD UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device C4:27:B0:5B:96:CD UUIDs: 98f00001-3788-83ea-453e-f52244709ddb
[CHG] Device C4:27:B0:5B:96:CD ServicesResolved: yes
[CHG] Device C4:27:B0:5B:96:CD Paired: yes
[NEW] Primary Service (Handle 0xf170)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000a
        00001801-0000-1000-8000-00805f9b34fb
        Generic Attribute Profile
[NEW] Characteristic (Handle 0xdf10)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000a/char000b
        00002a05-0000-1000-8000-00805f9b34fb
        Service Changed
[NEW] Descriptor (Handle 0xea30)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000a/char000b/desc000d
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[NEW] Primary Service (Handle 0xf170)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000e
        98f00001-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xdf10)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000e/char000f
        98f00002-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Characteristic (Handle 0xdf10)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000e/char0011
        98f00003-3788-83ea-453e-f52244709ddb
        Vendor specific
[NEW] Descriptor (Handle 0x4910)
        /org/bluez/hci0/dev_C4_27_B0_5B_96_CD/service000e/char0011/desc0013
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Pairing successful
```

При добавлении через интеграцию ошибка теперь другая:
![image](https://user-images.githubusercontent.com/58520228/133930699-257e1fd0-63ba-42e4-88de-6b00978e758a.png)
В логах:
```
2021-09-19 21:11:03 DEBUG (MainThread) [custom_components.tion.config_flow] Going create entry with name Tion Breezer
2021-09-19 21:11:03 DEBUG (MainThread) [custom_components.tion.config_flow] {'name': 'Tion Breezer', 'keep_alive': 60, 'away_temp': 15, 'pair': False, 'mac': 'C4:27:B0:5B:96:CD', 'model': 'Lite'}
2021-09-19 21:11:03 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-19 21:11:03 WARNING (MainThread) [tion_btle.tion] Got BTLEDisconnectError:Failed to connect to peripheral C4:27:B0:5B:96:CD, addr type: random
2021-09-19 21:11:03 DEBUG (MainThread) [tion_btle.tion] Will try again.
2021-09-19 21:11:05 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-19 21:11:06 WARNING (MainThread) [tion_btle.tion] Got BTLEDisconnectError:Failed to connect to peripheral C4:27:B0:5B:96:CD, addr type: random
2021-09-19 21:11:06 ERROR (MainThread) [custom_components.tion.config_flow] Could not get data from breezer. result is {}, error: Failed to connect to peripheral C4:27:B0:5B:96:CD, addr type: random
2021-09-19 21:11:08 DEBUG (MainThread) [custom_components.tion.config_flow] Add failed. Returning to first step
```

**Comment by xcraftster** [comment]
> Добрый день.
> 
> При попытке подключиться через bluetoothctl получаю ошибку:
> 
> ```
> [bluetooth]# pair C4:27:B0:5B:96:CD
> Device C4:27:B0:5B:96:CD not available
> ```
> 
> Посмотрел FAQ. Кажется советы не подходят: к бризеру никто не подключен, Home Assistant как я понимаю на HASS OS работает из под root, разрешения для root в `bluetooth.conf` есть.

Попробуйте перевести бризер в режим сопряжения, потом scan on (в bluetoothctl) и через несколько секунд pair MAC-бризера

**Comment by dmdmvl** [comment]
> У меня было так тоже. Попробуйте перевести бризер в режим сопряжения, потом scan on (в bluetoothctl) и через несколько секунд pair MAC-бризера

Примерно так и сделал, только сначала включил сканирование, затем бризер в режим сопряжения (в этот момент бризер появился в списке устройств), затем pair MAC. Однако в HA бризер так и не подключается :(

**Comment by IATkachenko** [comment]
Угу, 10 минут подождать, потом добавить в НА без сопряжения. Магия должна сработать.
И проверьте что при сопряжении правильно ключи передались (тоже в Wiki про это).

**Comment by dmdmvl** [comment]
Попробовал подождать и подключиться - не помогло. Пробовал ждать от 5 минут до нескольких часов.
Проверил версию с ключами, у меня вообще нет папки `/var/lib/bluetooth`. 

Затем попробовал так:
1) Перевел бризер в режим сопряжения
2) При подключении в HA убрал галочку необходимости сопряжения
После этого бризер подключился. Уже лучше :)

Теперь новые проблемы, бризер работает очень нестабильно. При попытке управлять из карточки HA регулярно отображается сообщение об ошибке вызова сервиса, при этом команды на бризер приходят через раз. 
В логах при этом ошибки подобного вида:
```
2021-09-20 10:25:31 INFO (MainThread) [custom_components.tion.climate] Need to set mode to heat, current mode is heat
2021-09-20 10:25:31 INFO (MainThread) [custom_components.tion] Need to set: heater='off', state='on'
2021-09-20 10:25:31 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-20 10:25:32 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-09-20 10:25:32 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 10:25:32 DEBUG (MainThread) [tion_btle.tion] Will write b'\x01\x00' to 19 handle with withResponse=True
2021-09-20 10:25:32 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2021-09-20 10:25:32 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] First read done. Data is c000000000000a14190204060627009626
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a4c31120dd71f8fa4b671d4cfd8021906
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 400d171cd1cd03001aac03003b44ec0026c30300
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000000000100000000
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a1419020406063000d9eb
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.lite] Data is cfd80219060d171cd1cd03001aac03003b44ec0026c303000000000000000000000000000000010000000000000000000a1419020406063000
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b'\x00\x1e\x00:|0\x12\xd3@P\xb0\xe2t\xa2Q\x07\x00\x02\x19\x06\n\x14\x19\x02\x04\x06`\x00\x00\xbb\xaa')
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Writing 001e003a7c3012d34050b0e274a2510700021906 to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Writing c00a1419020406600000bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Disabling notifications
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Will write b'\x00\x00' to 19 handle with withResponse=True
2021-09-20 10:25:33 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a313112d34050b0e274a2518fd8021906
2021-09-20 10:25:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548178175408] Unexpected response (wr)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/config/custom_components/tion/climate.py", line 256, in async_set_hvac_mode
await self._async_set_state(heater=False, is_on=True)
File "/config/custom_components/tion/climate.py", line 432, in _async_set_state
await self._tion_entry.set(**kwargs)
File "/config/custom_components/tion/__init__.py", line 205, in set
self.__tion.set(kwargs)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 264, in set
self.disconnect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 567, in disconnect
self._disconnect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 333, in _disconnect
self._disable_notifications()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 398, in _disable_notifications
self.__write_to_notify_handle(setup_data)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 372, in __write_to_notify_handle
result = self._btle.writeCharacteristic(notify_handle, data, withResponse=need_response)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
return self._getResp('wr')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 416, in _getResp
self.delegate.handleNotification(hnd, data)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 23, in handleNotification
self.__topic.read()
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
return self.peripheral.readCharacteristic(self.valHandle)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
resp = self._getResp('rd')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (wr)
```

**Comment by IATkachenko** [comment]
То что удалось победить подключение -- хорошо.

Можете поправить `/usr/local/lib/python3.9/site-packages/tion_btle/tion.py`?
351-352 строки нужно привести к виду
```python
    def __write_to_notify_handle(self, data):
        need_response = False
```
На 3S и 4S мы тестировали отказ от ответа при подписке на уведомления, а на Lite -- нет. Если станет лучше -- уберу и для Lite.

И еще подскажите, пожалуйста, на какой OS (название версия) работает система. Плюс интересует версия bluez.
_(собственно ноги растут из взаимодействия устройств на уровне bluetooth-стека. 
У python-модуля компонента известные проблемы с этим и идеальной стабильной работы у меня добиться не получается: дома ошибки проскакивают регулярно, но работе не мешают и связанны, в основном, с неожиданными отключениями при передаче команд)_

**Comment by dmdmvl** [comment]
После изменения в tion.py и перезагрузки HA бризер перестал отвечать. В логе следующие ошибки:
```
2021-09-20 18:43:37 DEBUG (MainThread) [custom_components.tion] Tion instance updated at 2021-09-20 11:43:37.874883+00:00
2021-09-20 18:43:37 DEBUG (MainThread) [custom_components.tion] Update fired force = False. Keep connection is False
2021-09-20 18:43:37 DEBUG (MainThread) [custom_components.tion] Now is 2021-09-20 11:43:37.874883+00:00
2021-09-20 18:43:37 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-20 18:43:38 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-09-20 18:43:38 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 18:43:38 DEBUG (MainThread) [tion_btle.tion] Will write b'\x01\x00' to 19 handle with withResponse=False
2021-09-20 18:43:38 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2021-09-20 18:43:38 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-09-20 18:43:39 DEBUG (MainThread) [tion_btle.tion] First read done. Data is c000000000000a14190204060616000fbc
2021-09-20 18:43:39 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-09-20 18:43:39 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 18:43:39 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 18:43:49 DEBUG (MainThread) [tion_btle.tion] Disabling notifications
2021-09-20 18:43:49 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 18:43:49 DEBUG (MainThread) [tion_btle.tion] Will write b'\x00\x00' to 19 handle with withResponse=False
2021-09-20 18:43:49 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2021-09-20 18:43:49 DEBUG (MainThread) [tion_btle.tion] disable_notification is done
2021-09-20 18:43:49 CRITICAL (MainThread) [custom_components.tion] Response is {}
2021-09-20 18:43:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/tion/climate.py", line 437, in _async_update_state
await self._tion_entry.async_update_state(time, force, keep_connection)
File "/config/custom_components/tion/__init__.py", line 126, in async_update_state
raise e
File "/config/custom_components/tion/__init__.py", line 103, in async_update_state
response = self.__tion.get(keep_connection)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 223, in get
response = self._get_data_from_breezer()
File "/usr/local/lib/python3.9/site-packages/tion_btle/light_family.py", line 137, in _get_data_from_breezer
raise TionException("Lite _get_data_from_breezer", "Could not get breezer state")
tion_btle.tion.TionException: ('Lite _get_data_from_breezer', 'Could not get breezer state')
```

Вот вся информация о системе:
![image](https://user-images.githubusercontent.com/58520228/133999097-2f822ebc-129f-435e-a787-c0c9f92ef97f.png)

Версия bluez:
```
# bluetoothctl --version
bluetoothctl: 5.55
```

Также нашел файл с ключами bluetooth из FAQ (уж очень замороченная система в HASS OS, раньше смотрел не в том контейнере), ключи на месте.

**Comment by IATkachenko** [comment]
А где ключи нашли, если не секрет (дополню wiki)?

Лог выглядит прилично, просто бризер не отвечает... Если ситуация не изменится, то правку нужно откатить и этот параметр для Lite действительно важен...

В предыдущих логах от бризера приходил правильный ответ (первый лог), но на попытку записать данные данные bluepy получал неправильынй ответ: rd на запись данных и wr при чтении (а должно быть ровно наоборот, те данные доя сообщения статуса брались из какого-то кэша).

**Comment by dmdmvl** [comment]
По умолчанию SSH аддон открывает контейнер где запущен HA, а для чтения файла с ключами необходимо подключиться к HASS OS по инструкции отсюда https://developers.home-assistant.io/docs/operating-system/debugging/, затем ключи можно найти по пути описанному в FAQ.

Связь с бризером не восстановилась. Попробовал удалить из HA, но добавить снова уже не смог. Откатил правку, после этого бризер добавился в систему. Ошибки не исчезли :( Например попытался сменить скорость, скорость фактически изменилась, но HA показывает ошибку
```
2021-09-20 19:41:56 INFO (MainThread) [custom_components.tion] Need to set: fan_speed=4, state='on'
2021-09-20 19:41:56 DEBUG (MainThread) [tion_btle.tion] Connecting
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Enabling notification
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Will write b'\x01\x00' to 19 handle with withResponse=True
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Result is {'rsp': ['wr']}
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Delegation enabled
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] First read done. Data is c000000000000a14190204060621006052
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] enable_notification is done
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Writing 8010003a0232120dd71f8f48d3c31abbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a9c31120dd71f8f886181aecfd8021903
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 400d191ebc250400d300040082efeb00b6140500
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 4000000000000000000000000000000100000000
2021-09-20 19:41:57 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response c000000000000a1419020406060c00c41f
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.lite] Data is cfd80219030d191ebc250400d300040082efeb00b61405000000000000000000000000000000010000000000000000000a1419020406060c00
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b'\x00\x1e\x00:\x840\x12\x98D\x0e\x07\x9b-G\xd1\x17\x00\x02\x19\x04\n\x14\x19\x02\x04\x06`\x00\x00\xbb\xaa')
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Writing 001e003a84301298440e079b2d47d11700021904 to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Doing _try_write. Attempt 1/3
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Writing c00a1419020406600000bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Disabling notifications
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Notify handler is 18
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Will write b'\x00\x00' to 19 handle with withResponse=True
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 0049003a81311298440e079b2d47d1cfd8021904
2021-09-20 19:41:58 DEBUG (MainThread) [tion_btle.tion] Got data in 18 response 400d191ebc250400d300040082efeb00b6140500
2021-09-20 19:41:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548070360544] Unexpected response (wr)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/config/custom_components/tion/climate.py", line 376, in async_set_fan_mode
await self._async_set_state(fan_speed=fan_mode, is_on=True)
File "/config/custom_components/tion/climate.py", line 432, in _async_set_state
await self._tion_entry.set(**kwargs)
File "/config/custom_components/tion/__init__.py", line 205, in set
self.__tion.set(kwargs)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 264, in set
self.disconnect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 567, in disconnect
self._disconnect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 333, in _disconnect
self._disable_notifications()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 398, in _disable_notifications
self.__write_to_notify_handle(setup_data)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 372, in __write_to_notify_handle
result = self._btle.writeCharacteristic(notify_handle, data, withResponse=need_response)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
return self._getResp('wr')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 416, in _getResp
self.delegate.handleNotification(hnd, data)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 23, in handleNotification
self.__topic.read()
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
return self.peripheral.readCharacteristic(self.valHandle)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
resp = self._getResp('rd')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 416, in _getResp
self.delegate.handleNotification(hnd, data)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 23, in handleNotification
self.__topic.read()
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
return self.peripheral.readCharacteristic(self.valHandle)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
resp = self._getResp('rd')
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (wr)
```

Заметил интересный момент во время правки tion.py, версия файла отличается от последней версии этого файла в репозитории https://github.com/TionAPI/tion_python/blob/master/tion_btle/tion.py. Кажется в манифесте компонента прописана более старая версия 1.3.2 https://github.com/TionAPI/HA-tion/blob/master/custom_components/tion/manifest.json. Может ли это как-то повлиять на работу бризера?

**Comment by IATkachenko** [comment]
Спасибо, сейчас дополню wiki.

Касательно эксперимента: значит для Lite важна опция WithResponse, спасибо.
Существенные различия между 1.3.2 и 1.3.3 (master) только в этом коммите https://github.com/TionAPI/tion_python/commit/833b3736860afe7c6d5b585cee3c8776411cdfd6
Он убирает некотоыре проблемы, котоыре возникали после выполнения всех команд и отключения от бризера. Можно локально, в манифесте прописать версию 1.3.3. Это может помочь на уровне "магии", поскольку в логе я вижу что во время записи приходит ответ от бризера и все ломается (в норме это не должно вызывать проблем).

Работает вся эта кухня так: при изменении параметров HA подключается к бризеру, читает текущее состояние, выставляет параметры, отключается, подключается для обновления текущего состояния. Еще можно будет попробовать больше доверять модулю и не делать get после set. Это тоже снимит некоторые пробелмы. Давайте в этом ключе попробуем...

В вашем случае процедура отключения и получение новых данных произошли одновременно. blupy ни разу не паралельный и с этим не справился. Уйти на bleak пока возможности нет.

**Comment by dmdmvl** [comment]
Заменил в манифесте версию на 1.3.3.
Отправил бризеру более 30 команд, пока ни одной ошибки (раньше 2/3 были с ошибками).
Продолжаю тестировать.

**Comment by IATkachenko** [comment]
Интересно...
Тогда релиз с модулем v1.3.3 сделаю на днях, чтобы все получили обновление.
Удаление дополнительного подключения/запроса тоже почти готово. Думаю к выходным будет релиз и с этой штукой.

**Comment by dmdmvl** [comment]
@IATkachenko За сутки тестирования не было ни одной ошибки. Магия сработала :)
