### ISSUE TITLE
Не меняется в HA режимы работы бризера

### ISSUE THREAD

**Issue by MihVS** [TionAPI/HA-tion#55]
При изменении например скорости на бризер команда приходит и он выполняет, но в НА пишет ошибку и не видит что бризер поменял скорость.
Бризер лайт.

`Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/tion/__init__.py:103
Integration: Tion breezer (documentation)
First occurred: 10:41:49 (1 occurrences)
Last logged: 10:41:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tion/climate.py", line 437, in _async_update_state
    await self._tion_entry.async_update_state(time, force, keep_connection)
  File "/config/custom_components/tion/__init__.py", line 126, in async_update_state
    raise e
  File "/config/custom_components/tion/__init__.py", line 103, in async_update_state
    response = self.__tion.get(keep_connection)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 222, in get
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 559, in connect
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 307, in _connect
    if self.connection_status == "disc":
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 297, in connection_status
    raise e
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 292, in connection_status
    connection_status = self._btle.getState()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 471, in getState
    status = self.status()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 379, in status
    return self._waitResp(['stat'])
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
    raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (rd)
`

**Comment by MihVS** [comment]
Добавляю логи  из НА с включенным логированием.

Общий вид:
<
Error doing job: Task exception was never retrieved
11:04:13 – (ОШИБКА) Tion breezer (кастомная интеграция) - первое сообщение получено 11:03:13 и повторялось 2 раз
Response is {}
11:04:13 – (КРИТИЧЕСКАЯ ОШИБКА) Tion breezer (кастомная интеграция) - первое сообщение получено 11:03:13 и повторялось 2 раз
Will delay next check
11:04:11 – (КРИТИЧЕСКАЯ ОШИБКА) Tion breezer (кастомная интеграция)
Got exception Failed to connect to peripheral FB:17:6F:12:42:DD, addr type: random
11:04:11 – (КРИТИЧЕСКАЯ ОШИБКА) Tion breezer (кастомная интеграция)
Got BTLEDisconnectError:Failed to connect to peripheral D8:2C:C6:F3:3B:AA, addr type: random
11:04:11 – (ПРЕДУПРЕЖДЕНИЕ) /usr/local/lib/python3.9/site-packages/tion_btle/tion.py - первое сообщение получено 11:01:11 и повторялось 6 раз
tion_speed_bedroom_repeat: Error executing script. Unexpected error for call_service at pos 2: Unexpected response (rd)
11:03:49 – (ОШИБКА) Автоматизация (кастомная интеграция) - первое сообщение получено 11:01:30 и повторялось 12 раз
Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'
11:03:17 – (ПРЕДУПРЕЖДЕНИЕ) helpers/template.py - первое сообщение получено 11:00:15 и повторялось 37 раз
apply_speed_bedroom_tion: Error executing script. Unexpected error for call_service at pos 2: Unexpected response (wr)
11:03:04 – (ОШИБКА) Автоматизация (кастомная интеграция) - первое сообщение получено 11:01:17 и повторялось 4 раз
>

Критическая ошибка:
<
Logger: homeassistant.components.automation.tion_speed_bedroom_repeat
Source: custom_components/tion/__init__.py:205
Integration: Автоматизация (documentation, issues)
First occurred: 11:01:30 (12 occurrences)
Last logged: 11:03:49

tion_speed_bedroom_repeat: Error executing script. Unexpected error for call_service at pos 2: Unexpected response (rd)
While executing automation automation.tion_speed_bedroom_repeat
tion_speed_bedroom_repeat: Error executing script. Unexpected error for call_service at pos 2: Unexpected response (wr)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 376, in async_set_fan_mode
    await self._async_set_state(fan_speed=fan_mode, is_on=True)
  File "/config/custom_components/tion/climate.py", line 432, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 205, in set
    self.__tion.set(kwargs)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 255, in set
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 560, in connect
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 307, in _connect
    if self.connection_status == "disc":
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 297, in connection_status
    raise e
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 292, in connection_status
    connection_status = self._btle.getState()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 471, in getState
    status = self.status()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 379, in status
    return self._waitResp(['stat'])
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 375, in _waitResp
    raise BTLEInternalError("Unexpected response (%s)" % respType, resp)
bluepy.btle.BTLEInternalError: Unexpected response (rd)

>

**Comment by IATkachenko** [comment]
Добрый день.
В manifet.json пропишите версию tion-btle==1.3.3
В соседнем issue помогло с такмими проблемами...

**Comment by MihVS** [comment]
Не помогло, обратная связь очень с большой задержкой. Раньше такого не было. После лета проблему обнаружил. Летом бризер не использовал.

**Comment by IATkachenko** [comment]
А какая версия компонента у вас летом была (я могу по истории релизов восстановить, но если вы помните будет проще и быстрее)? Можно попробовать откатиться на версию tion-btle используемую в ней.
Но проблема очень похожа на обсуждаемую в #54 и переход на tion-btle==1.3.3 должен помочь...

**Comment by MihVS** [comment]
Тут скорее весной версию нужно смотреть, летом не пользовался. К сожалению не помню версию. В манифесте было прописано 1.3.2 поменял на 1.3.3 но проблема осталась. Пробовал откатиться до версии 1.7... не помогло. Даже не знаю в чем проблема. 
У меня после отправки команды бризеру НА ждёт 15 сек, проверяет статус и если не изменился отправляет повторно команду. И по факту получается что скрипт шлёт исправно команду на бризер(он каждый раз пищит) а ответ не получает. Но спустя какое то время статусы в НА всё таки меняется.

**Comment by IATkachenko** [comment]
Если с весны, то это версия 1.7.1 и версия модуля 1.2.0. 
Если откатиться не помогло, то проблема не с компонентом/модулем.

На чем у вас крутится управление бризером? 
У себя я заметил следующиее:
1. переход с Pi3B+ на Pi4 существенно ухудшил работу с бризером (вплоть до полной невозможности работать);
2. переход с встроенного bluetooth на внешний позволил с бризером работать хоть как-то;
3. вынос внешнего bluetooth на 10см от малины существенно улучшил качество работы.

**Comment by MihVS** [comment]
На pi4 у меня крутится на встроенном блютуз. Сейчас обновился до последней версии и о чудо стало всё чётко работать, буду наблюдать.

**Comment by IATkachenko** [comment]
Значит таки сработало обновление модуля до 1.3.3, как в #54.
