### ISSUE TITLE
Tion Lite управляются из Home Assistant через раз

### ISSUE THREAD

**Issue by kalend** [TionAPI/HA-tion#66]
## Общая информация
  * **версия Home Assistant**: 2021.12.9
  * **способ установки Home Assistant**: Docker
 * **версия компонента**: 2.1.3
 * **модель бризера**: Lite
в момент проявления проблемы к бризеру никто не подключен
bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
Пытаюсь управлять тремя тионами из под Scheduler Component. Когда управляю "руками" - иногда управляются не с первого раза (как бы просыпаются), но потом рулятся нормально. 
При управления из Scheduler иногда часть тионов пропускает команду на включить-выключить и приходится потом их руками пинать. В логах при этом ошибка.

## Debug-log
Logger: homeassistant.core
Source: custom_components/tion/__init__.py:19 
Integration: Tion breezer (documentation) 
First occurred: 08:00:00 (3 occurrences) 
Last logged: 16:00:15

Error executing service: <ServiceCall climate.set_hvac_mode (c:9eeda46347a0f1a661e2941627abf3a0): hvac_mode=off, entity_id=['climate.detskaya']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:c08fddd63e49fd75629824346423830e): hvac_mode=off, entity_id=['climate.spalnya']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:1c50a3f3342dd384c2f30baa984f15a3): hvac_mode=heat, entity_id=['climate.spalnya']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 205, in async_set_hvac_mode
    await self._async_set_state(is_on=False)
  File "/config/custom_components/tion/climate.py", line 407, in _async_set_state
    await self._tion_entry.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 194, in set
    await btle_exec_helper(self.__tion.set, kwargs)
  File "/config/custom_components/tion/__init__.py", line 19, in btle_exec_helper
    return await asyncio.wrap_future(_BTLE_COMMAND_EXECUTOR.submit(method, *args, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 294, in set
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 586, in connect
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 368, in _connect
    raise e
  File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 349, in _connect
    self._btle.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral fc:2c:c1:7c:f9:dc, addr type: random

Сейчас попробую на последнюю версию Вашу переехать...

**Comment by IATkachenko** [comment]
Вроде в #60 вы говорили что перешли на 2.1.3 и проблема ушла? Или я вас не правильно понял?

По логу, без timestamp, понять одновременно ли происходит попытка обратиться к bluetooth не возможно, но думаю что это именно та проблема с которой боролся @kizill в релизе 2.1.3 и странно что вы ее видите...

**Comment by kalend** [comment]
Игорь как оказалось - поспешил с выводами. Действительно сразу после обновления проблемы не заметил, но прошло 1-2 суток и стал видеть как пропуски идут в шедулере. 
Bluetooth кстати сам по себе работает четко - я обратил внимание еще вот на что. Если я обращаюсь из штатного приложения Тион, то при запуске приложения он тоже не всегда тион лайт находит. Для этого у них есть кнопочка refresh. Т.е. сами по себе эти железки не всегда цепляются по первому разу. Похоже нужно в алгоритм где-то заложить возможность повторных реконнектов.

**Comment by kalend** [comment]
Логи файликом за вчера цепляю, а ниже фрагмент из лог файла несколько минут назад
2022-01-18 11:35:39 CRITICAL (MainThread) [tion_btle.tion] Retry limit (1) exceeded for _try_connect((<tion_btle.lite.Lite object at 0xad7719d0>,), {})
2022-01-18 11:35:39 CRITICAL (MainThread) [custom_components.tion] Response is {}
2022-01-18 11:35:39 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/tion/climate.py", line 412, in _async_update_state
await self._tion_entry.async_update_state(time, force, keep_connection)
File "/config/custom_components/tion/__init__.py", line 120, in async_update_state
raise e
File "/config/custom_components/tion/__init__.py", line 106, in async_update_state
response = self.__tion.get(keep_connection)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 274, in get
self.get_state_from_breezer(keep_connection)
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 249, in get_state_from_breezer
self.connect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 598, in connect
self._connect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 371, in _connect
self._try_connect()
File "/usr/local/lib/python3.9/site-packages/tion_btle/tion.py", line 43, in wrapper
raise MaxTriesExceededError
tion_btle.tion.MaxTriesExceededError

**Comment by IATkachenko** [comment]
Реконкеты уже есть (2 попытки подключиться 3 отправить запрос после подключения).
Видимо, следующий шаг -- вынести в пользовательские настрйоки сколько раз пытаться переподключиться / перезапросить данные, поскольку все очень индивидуально и сильно зависит от взаиморасположения.
В этом ключе тогда и двинусь.

ps. На полный debug лог в вашем случае очень хочется посмотреть: есть подозрение что что-то в retry части идет не так как задумано: `bluepy.btle.BTLEDisconnectError` наружу прорываться не должно.

**Comment by kalend** [comment]
Спасибо. Я погрепал на всякий случай на предмет bluepy.btle.BTLEDisconnectError - действительно в логах такой ругани нет.

**Comment by IATkachenko** [comment]
Ага, вижу, просто  лог из первого сообщения с этим exception, чего быть не должно...

**Comment by IATkachenko** [comment]
Хех, mybad: в 2.1.2 это починили, а в 2.1.3 я сломал. И заметил только сейчас. 

В 2.1.5 снова должно быть также хорошо как было поле правок @kizill и до того как я случайно частично откатил правку для опроса состояния.

**Comment by kalend** [comment]
Забавно. ;-) Обновил до 2.1.5. Смотрим.

**Comment by IATkachenko** [comment]
И еще один подход к этой проблеме в ветке [i83](https://github.com/TionAPI/HA-tion/tree/i83)/#83
