### ISSUE TITLE
Tion 4s ошибка при изменении скорости

### ISSUE THREAD

**Issue by H4pH** [TionAPI/HA-tion#70]
## Общая информация
  * **версия Home Assistant**: 2022.3.8
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker
    [ ] Home Assistant OS
 * **версия компонента**: v2.2.0
 * **модель бризера**:  S4  

[x] в момент проявления проблемы к бризеру никто не подключен
[x] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[x] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 
При изменении скорости в HA всплывает сообщение об ошибке, при этом скорость изменяется корректно.

## Debug-log
```
2022-03-31 13:50:12 INFO (MainThread) [custom_components.tion] Need to set: fan_speed=3, state='on'
2022-03-31 13:50:12 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Connecting
2022-03-31 13:50:12 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s4.S4 object at 0xa4ddc610>,),kwargs={})
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Enabling notification
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Notify handler is 18
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Will write b'\x01\x00' to 19 handle with withResponse=False
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Result is {'rsp': ['wr']}
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Delegation enabled
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] First read done. Data is c0000000000006008fd0
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] enable_notification is done
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.S4 object at 0xa4ddc610>,),kwargs={'request': bytearray(b'\x80\x10\x00:\xa122\x8eX\x15\xca\x84\x1d\xf45\xbb\xaa')})
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Writing 8010003aa132328e5815ca841df435bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Collecting data
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Got data in 18 response 002f003a9231328e5815cafbbd29523f41001402
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Got data in 18 response 400103151d1b13230019c92200e784ca008ecd77
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Got data in 18 response c0000000000006009e5b
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Will write bytearray(b'\x00\x17\x00:\x9602:\x94\xfa\'\x90"\x87\x84\x1f\x00\x00\x14\x03\xb5\x00\xbb\xaa')
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.S4 object at 0xa4ddc610>, bytearray(b'\x00\x17\x00:\x9602:\x94\xfa\'\x90"\x87\x84\x1f\x00\x00\x14\x03')),kwargs={})
2022-03-31 13:50:13 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Writing 0017003a9630323a94fa27902287841f00001403 to 98f00002-3788-83ea-453e-f52244709ddb
2022-03-31 13:50:14 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s4.S4 object at 0xa4ddc610>, bytearray(b'\xc0\xb5\x00\xbb\xaa')),kwargs={})
2022-03-31 13:50:14 DEBUG (ThreadPoolExecutor-0_0) [tion_btle.tion] Writing c0b500bbaa to 98f00002-3788-83ea-453e-f52244709ddb
2022-03-31 13:50:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2779049288] invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 671, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 708, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 209, in async_set_fan_mode
    await self._async_set_state(fan_speed=fan_mode, is_on=True)
  File "/config/custom_components/tion/climate.py", line 237, in _async_set_state
    await self.coordinator.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 129, in set
    kwargs["fan_speed"] = int(kwargs["fan_speed"])
ValueError: invalid literal for int() with base 10: ''
2022-03-31 13:50:40 INFO (MainThread) [custom_components.tion] Tion instance update started
```

## Как можно воспроизвети вашу проблему

1. зайти в карточку бризера
2. сменить скорость

**Comment by IATkachenko** [comment]
Спасибо. Проверю.
Лог выглядит прилично.

**Comment by IATkachenko** [comment]
Могу воспроизвести локально.

**Comment by IATkachenko** [comment]
Исправлено в [v2.2.1](https://github.com/TionAPI/HA-tion/releases/tag/v2.2.1)
