### ISSUE TITLE
Интеграция не работает в HA 2022.07

### ISSUE THREAD

**Issue by tms320** [TionAPI/HA-tion#88]
## Общая информация
  * **версия Home Assistant**: 2022.7.0
  * **способ установки Home Assistant**:
    [ ] venv
    [x] Docker (HA supervised)
    [ ] Home Assistant OS
 * **версия компонента**: 2.4.0
 * **модель бризера**: 4S 
 * **версия python-модуля**: 

[x] в момент проявления проблемы к бризеру никто не подключен
[?] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[?] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание
 
Использую Home Assistant Supervised, установленный в Ubuntu server 22.04 (не на "малинке", а на мини-ПК с Celeron'ом).
HACS-инсталляция прошла успешно. Проблема возникает на этом шаге:
![image](https://user-images.githubusercontent.com/24802646/177857609-f95cdb28-0e91-403d-ad0d-3904bb9c64c3.png)
После пары минут ожидания выскакивает сообщение:
![image](https://user-images.githubusercontent.com/24802646/177858213-e7c7f770-c06d-4d98-a41f-34b92c8a3839.png)
В логах HA такие две ошибки:
- Logger: homeassistant.util.package
 Source: util/package.py:99
 First occurred: 21:53:30 (3 occurrences)
 Last logged: 21:54:13
 Unable to install package tion-btle==1.5.1: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [8 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running bdist_wheel running build running build_py Working dir is /tmp/pip-install-t68557aj/bluepy_f877130ea7e842e489b13fe10f6f860c execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bluepy error: subprocess-exited-with-error × Running setup.py install for bluepy did not run successfully. │ exit code: 1 ╰─> [10 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py Working dir is /tmp/pip-install-t68557aj/bluepy_f877130ea7e842e489b13fe10f6f860c execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> bluepy note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.
- Logger: aiohttp.server
Source: requirements.py:267
First occurred: 21:54:13 (1 occurrences)
Last logged: 21:54:13
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 240, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 779, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 236, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tion not found: ['tion-btle==1.5.1'].

В хост-системе (мини-ПК) подключиться к бризеру в режиме сопряжения через bluetoothctl - получилось:
![image](https://user-images.githubusercontent.com/24802646/177859357-e447eb93-a8c4-4767-997a-9397b8b8b031.png)
Проверить остальные вещи, указанные в WiKi - не знаю как, извините (я ведь не сам запускаю докер-контейнеры)...

**Comment by fishenebelny** [comment]
Скорее всего проблема в версии Home Assistant, которая пепестала поддерживать bluepy, который в текущем варианте нужен для работы интеграции.
Попробуйте 2022.06.

**Comment by tms320** [comment]
PS: при повторной попытке установить интеграцию:
![image](https://user-images.githubusercontent.com/24802646/177861433-1c697e29-0997-4fb9-a266-249d91969ce3.png)

Появляется это:
![image](https://user-images.githubusercontent.com/24802646/177861485-4976c1cc-b225-4247-9c68-a6928e340089.png)

**Comment by IATkachenko** [comment]
@tms320 посмотрите #86 / #87

HA 2022,7 будет поддерживаться только в следующем релизе, v3.0.0.
В статусе betta-релиза я его планирую сделать уже в выходные: на S3 у меня все работает корректно, но я хотел бы еще получить результаты тестирования новой версии модуля на бризерах семейства Lite. Если у вас есть такой бризер и достаточная квалификация -- тоже можете помочь с тестами инструкции и обсуждение здесь: https://github.com/TionAPI/tion_python/pull/39#issuecomment-1177907807

**Comment by tms320** [comment]
Вынужден продолжить свою тему )
Я на месяц уезжал, поэтому не имел возможности заниматься этим вопросом.
Но вот я приехал. Обновил HA до версии 2022.8.0 (Supervisor 2022.07.0).
Как я понял из обсуждения, за время моего отсутствия была выпущена новая версия интеграции, где сделан переход на bleak, что должно решить обсуждавшуюся здесь проблему.
Через HACS установил заново интеграцию "Tion breezer" v3.0.2.
Далее, вот на этом шаге:
![image](https://user-images.githubusercontent.com/24802646/182919362-a0aa3975-1895-4c50-aa88-271d94e241e6.png)
появляется ошибка:
![image](https://user-images.githubusercontent.com/24802646/182919385-33c0bb1d-50e7-4daa-ba75-d97d7f72360c.png)
В логах HA вот такое:

- Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 20:46:14 (3 occurrences)
Last logged: 20:46:28
Unable to install package tion-btle==2.0.6: ERROR: Cannot install tion-btle==2.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
 
- Logger: aiohttp.server
Source: requirements.py:267
First occurred: 20:46:28 (1 occurrences)
Last logged: 20:46:28
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 240, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 791, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 362, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 236, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tion not found: ['tion-btle==2.0.6'].

**Comment by IATkachenko** [comment]
Если вы думаете что HA `2022.7` не отличается от `2022.8`, то вы ошибаетесь. И, как видно из сообщения об ошибке, оно не похоже на то, что вы видели в `2022.7`.

Проблемы для HA `2022.7`, про которые это issue (как следует из заголовка и первого сообщения), решены. Проблемы `2022.8` -- нет #102.

Это -- основная причина, почему следует пользоваться принципом "одна проблема == одно issue" и не валить все в одну кучу.

**Comment by tms320** [comment]
Спасибо. Учту ваше замечание.
