### ISSUE TITLE
Ошибка "dictionary changed size during iteration"

### ISSUE THREAD

**Issue by fishenebelny** [TionAPI/HA-tion#94]
## Общая информация
  * **версия Home Assistant**: 2022.7.2
  * **способ установки Home Assistant**:
    [ ] venv
    [*] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 3.0.0
 * **модель бризера**: S3
 * **версия python-модуля**: 

[*] в момент проявления проблемы к бризеру никто не подключен
[*] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[*] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)

## Краткое описание 

При изменение скорости работы тиона, изменения состояни и пресетов в некоторых случаях появлялась ошибка `dictionary changed size during iteration`
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tion/__init__.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9 июля 2022 г., 21:45:11 (13 occurrences)
Last logged: 10 июля 2022 г., 10:10:22

[2612522528] dictionary changed size during iteration
[2603551664] dictionary changed size during iteration
[2894994544] dictionary changed size during iteration
[2600046040] dictionary changed size during iteration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/tion/climate.py", line 211, in async_set_fan_mode
    await self._async_set_state(fan_speed=fan_mode, is_on=True)
  File "/config/custom_components/tion/climate.py", line 239, in _async_set_state
    await self.coordinator.set(**kwargs)
  File "/config/custom_components/tion/__init__.py", line 134, in set
    for update_callback in self._listeners:
RuntimeError: dictionary changed size during iteration
```

## Debug-log
```
2022-07-10 10:10:18 INFO (MainThread) [custom_components.tion.climate] Need to set mode to heat, current mode is off
2022-07-10 10:10:18 DEBUG (MainThread) [tion_btle.tion] Connecting. self.connection_status='disc'.
2022-07-10 10:10:18 DEBUG (MainThread) [tion_btle.tion] Trying 0/1: _try_connect(args=(<tion_btle.s3.TionS3 object at 0xadcf0088>,),kwargs={})
2022-07-10 10:10:19 DEBUG (MainThread) [tion_btle.tion] Enabling notification. self.connection_status='connected'
2022-07-10 10:10:19 DEBUG (MainThread) [tion_btle.tion] _enable_notifications done
2022-07-10 10:10:19 DEBUG (MainThread) [tion_btle.tion] _connect done. self.connection_status='connected'.
2022-07-10 10:10:19 INFO (MainThread) [custom_components.tion] Need to set: heater='on', state='on'
2022-07-10 10:10:19 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s3.TionS3 object at 0xadcf0088>,),kwargs={'request': bytearray(b'=\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z')})
2022-07-10 10:10:19 DEBUG (MainThread) [tion_btle.tion] Writing 3d0100000000000000000000000000000000005a to 6e400002-b5a3-f393-e0a9-e50e24dcca9e, self.connection_status='connected'
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Got data in 10 response b3102207030017171651000900002d170133005a
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\xb3\x10"\x07\x03\x00\x17\x17\x16Q\x00\t\x00\x00-\x17\x013\x00Z')]
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Collecting data
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.s3] Data is b3102207030017171651000900002d170133005a
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Will write bytearray(b'=\x02\x02\x07\x02\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z')
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Trying 0/3: _try_write(args=(<tion_btle.s3.TionS3 object at 0xadcf0088>, bytearray(b'=\x02\x02\x07\x02\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z')),kwargs={})
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Writing 3d0202070203000000000000000000000000005a to 6e400002-b5a3-f393-e0a9-e50e24dcca9e, self.connection_status='connected'
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Got data in 10 response b3202207030017171651000900002d170133005a
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] self._data=[bytearray(b'\xb3 "\x07\x03\x00\x17\x17\x16Q\x00\t\x00\x00-\x17\x013\x00Z')]
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Collecting data
2022-07-10 10:10:20 DEBUG (MainThread) [tion_btle.tion] Disconnecting. self.connection_status='connected'.
2022-07-10 10:10:22 DEBUG (MainThread) [tion_btle.tion] _disconnect done. self.connection_status='disc'
2022-07-10 10:10:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2600046040] dictionary changed size during iteration
```

## Как можно воспроизвети вашу проблему

1. Нажать на любую кнопку управления тиона из ХА
Вообще по логам, проблема как будто не с тионом...

## Дополнительное описание

Произошло после обновления на 2022.7. До этого подобных проблем не было.

**Comment by IATkachenko** [comment]
В #92 это тоже всплыло: хотел тащить в отдельное issue, но меня опередили :)

Я там не корректно рассылаю обновленное состояние. Как сделать правильно уже знаю. Почему всплыло сейчас -- не знаю.
Фикс будет, думаю, ближе к ночи.

**Comment by fishenebelny** [comment]
У меня вот это вот "dictionary changed size during iteration" перестал появляться после того, как я вошел в настройки интеграции и просто нажал настроить. Лог с 9 июля полный есть, но когда я там это нажимал я не помню.

**Comment by IATkachenko** [comment]
Исправлено в [v3.0.1](https://github.com/TionAPI/HA-tion/releases/tag/v3.0.1).
