### ISSUE TITLE
Ошибка после обновления HA, HACS, TION

### ISSUE THREAD

**Issue by kalend** [TionAPI/HA-tion#99]
## Общая информация
  * **версия Home Assistant**: 2022.7.5
  * **способ установки Home Assistant**:
    [ ] venv
    [V ] Docker
    [ ] Home Assistant OS
 * **версия компонента**: 3.0.1
 * **модель бризера**: lite
## Краткое описание 

После обновления системы - не хочет нормально устанавливаться в интеграции связь с Бризером. Интеграция выдает ошибку Повторная настройка: [Errno 2] No such file or directory

Выдается ошибка от отсутствии файла в журнале сервера:
Unexpected error fetching data: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/tion/__init__.py", line 103, in async_update_state
    raise e
  File "/config/custom_components/tion/__init__.py", line 93, in async_update_state
    response = await self.__tion.get()
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 205, in get
    await self.get_state_from_breezer()
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 185, in get_state_from_breezer
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 502, in connect
    await self._connect()
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 299, in _connect
    await self._try_connect()
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 28, in wrapper
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tion_btle/tion.py", line 292, in _try_connect
    return await self._btle.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 88, in start
    self._bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by IATkachenko** [comment]
Там в шаблоне issue нужно проставить галочки. Не надо это игнорировать:
```
<!-- отметьте x если верно что: -->
[ ] в момент проявления проблемы к бризеру никто не подключен
[ ] bluetooth в системе работает корректно, действий из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth) не требуется
[ ] проблема не похожа ни на одну из [FAQ](https://github.com/TionAPI/HA-tion/wiki/FAQ)
```
Не плохо бы их не просто проставить, а и убедится что это соответвует действительности.

Ваша проблема, судля по всему, из [WiKi](https://github.com/TionAPI/HA-tion/wiki/Bluetooth), части "если Home Assistnat запущен в контейнере".

И, похоже,[release notes](https://github.com/TionAPI/HA-tion/releases/tag/v3.0.0) тоже не читают:
```
migrate to bleak-based version of tion_btle module ([21bdb3e](https://github.com/TionAPI/HA-tion/commit/21bdb3e62f2d725a98f526c055fc67b9f4a2e014)) closes https://github.com/TionAPI/HA-tion/issues/88, https://github.com/TionAPI/HA-tion/issues/87, https://github.com/TionAPI/HA-tion/issues/83, https://github.com/TionAPI/HA-tion/issues/66

    We are using bleak Bluetooth back-end now. It cool, fast and async. Make sure that /var/run/dbus and /dev/bus/usb is available in Home Assistant docker container (for Docker- ans Supervisor-based installations).
```

Проверьте что установка контейнера у вас  корректная.

**Comment by kalend** [comment]
нужен upgrade python

**Comment by IATkachenko** [comment]
У вас же контейнерная установка. Он сам все что нужно в себе тащит.

**Comment by kalend** [comment]
Да, согласен. Странно тогда - не получилось эту ошибку побороть. Не могу понять какого файла не хватает.

**Comment by kalend** [comment]
Спасибо, разобрался. Действительно контейнер некорректно запускал. Пришлось еще помучаться и вручную попривязывать через bluetoothctrl

**Comment by IATkachenko** [comment]
```
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
device = await BleakScannerBlueZDBus.find_device_by_address(
File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
return await cls.find_device_by_filter(
```
Вот этот кусок про то, что `bleak` не видит бризер через BT-стек системы.
`bluepy` и bluetoothctl работают через другое место.

**Comment by IATkachenko** [comment]
А я понял что вы имели в виду когда говорили "обновить питон".
`2022.7.5`, похоже, имеет туже болезнь, из-за которой мы не могли перейти на `bleak` раньше: python-модули для bluetooth(`pybluez`) есть не под все платформы, а собрать их контейнер не может.
В результате все, что на это полагается не работает, а в логах -- чудеснейшие трейсы из-за отсутствия `gcc` в контейнере.
Что интересно, в 2022.6.x -- все хорошо.
Сейчас 2022.7.6 проверю.

**Comment by IATkachenko** [comment]
Решение, кстати, простое и тоже из документации (на сей раз HA): отключить `bluetooth_tracker`, поскольку начиная с `2022.7` он не работает.
